boostcampwm2023/web17_morak

README.md
=> [Docs] README에 팀원 정보 추가

README.md
=> [Docs] README의 기획서 링크 수정

backend/.eslintrc.js, backend/.gitignore, backend/.prettierrc, backend/README.md, backend/nest-cli.json, backend/package-lock.json, backend/package.json, backend/src/app.controller.spec.ts, backend/src/app.controller.ts, backend/src/app.module.ts, backend/src/app.service.ts, backend/src/main.ts, backend/test/app.e2e-spec.ts, backend/test/jest-e2e.json, backend/tsconfig.build.json, backend/tsconfig.json
Backend NestJS 프로젝트 초기 세팅을 진행하였습니다.
=> [Feat] Backend NestJS 프로젝트 초기 세팅

backend/.dockerignore, backend/Dockerfile
- node 20 버전(LTS)로 이미지 서버 이미지 말 수 있도록 Dockerfile 작성
=> [Feat] 🔨 Nest JS 서버 Dockerfile 작성

.github/CODEOWNERS
=> [Docs] CODEOWNER 파일 추가

backend/package-lock.json, backend/package.json, backend/src/main.ts
=> [Feat] NestJS API 문서화를 위한 Swagger 설정

.gitignore
모노레포 gitignore 설정
- close #27 
dist, node_modules를 gitignore 처리하였습니다.
=> [Feat] 모노레포 gitignore 설정

README.md
README에 커맨드 실행 명령어 설명 추가합니다.
용어 관련하여 변경하고 싶은 부분 있다면 편하게 코멘트 주세요
=> [Docs] README에 모노레포 커맨드 실행 명령어 설명 추가

README.md
=> [Docs] README에 피그마 링크 추가

.github/CODEOWNERS
- 모노레포 구조 변경으로 인한 CODEOWNERS 파일 수정
=> [Docs] 모노레포 구조 변경으로 인한 CODEOWNERS 파일 수정

app/frontend/package.json, app/frontend/src/App.css.ts, app/frontend/src/App.tsx, app/frontend/vite.config.ts, package-lock.json
- #8 
X
X
- import/export 룰 `import { style, globalStyle, globalKeyframes } from '@vanilla-extract/css'`와 같은 중괄호 내 변수/메소드 등도 정렬이 되었으면 좋겠네요! 
→ 이슈로 생성해 두면 좋을 것 같아요
- (곧 삭제될 파일이지만) 우선 vanilla extract 예시로 App.css를 App.css.ts로 작성해 보았습니다. 처음에는 공식 문서를 많이 참고해야 할 것 같네요! 
- vanilla extract는 아직 stylelint 지원 플러그인이 없는 듯합니다. 
- [참고 1](https://stylelint.io/migration-guide/to-15/)
> If you create a new custom syntax, please [open a pull request](https://github.com/stylelint/awesome-stylelint/compare) to update [Awesome Stylelint](https://github.com/stylelint/awesome-stylelint#readme) so that others can find it. For example, [Stitches](https://stitches.dev/) and [vanilla-extract](https://vanilla-extract.style/) need syntaxes, which are object-based CSS-in-JS libraries.
- [참고 …
=> [Design] vanilla extract 설치 및 예시 코드 작성

app/frontend/package.json, package-lock.json, packages/eslint-config/frontend.js
=> [Chore] React Query | Jotai | Axios 라이브러리 설치

.gitignore
=> [Docs] gitignore에 .turbo 추가

.husky/pre-commit, app/frontend/package.json, app/frontend/src/App.tsx, package-lock.json, package.json
- closed #6
- 각자 로컬에서도 한 번씩 테스트해 보시면 좋을 것 같습니다.
- 참고: [Enforce Husky Pre-Commit With ESLint & Prettier In Monorepo - DEV Community](https://dev.to/monfernape/enforce-husky-pre-commit-with-eslint-prettier-in-monorepo-55jc)
=> [Chore] husky pre-commit 세팅

app/backend/package.json, app/backend/src/auth/auth.controller.ts, app/backend/src/auth/auth.service.ts, app/backend/src/auth/dto/user.dto.ts, app/backend/src/main.ts, package-lock.json
- close #42 
로그인 과정이 구글 로그인이기 때문에 유효성검사에 대해서 특별히 많은 것을 넣지 않았습니다.
=> [Feat] Auth 유효성 검사 및 Swagger 문서화 

app/backend/src/auth/auth.service.ts
- close #67 
기능 작업에 대한 스크린샷/화면 녹화 있을 경우 첨부하기
특별히 리뷰해 주었으면 하는 부분, 고민되는 부분 기재하기
=> [Fix] Secret Key, ExprisIn 환경변수 재설정

app/backend/Dockerfile, app/backend/docker-compose.yml, app/backend/docker-entrypoint.sh, app/backend/tsconfig.json, app/backend/wait-for-it.sh, packages/tsconfig/backend.json
백엔드 dockerfile 수정 및 docker compose 설정
- 프로젝트 루트 폴더에서 `docker compose -f app/backend/docker-compose.yml up --build` 를 수행하면 redis, nest, mysql (데이터 리셋) 서버가 뜹니다.
- 해당 기능을 통해 데이터의 영속성이 보장될 필요가 없는 로컬 서버와 개발 서버에 쓰기 좋아보입니다.
=> [Feat] 백엔드 docker 설정

app/frontend/.eslintrc.cjs, app/frontend/src/components/commons/Input/index.css.ts, app/frontend/src/components/commons/Input/index.tsx, app/frontend/src/components/index.ts, app/frontend/src/styles/reset.css.ts, packages/eslint-config/frontend.js
- closed #49 
디폴트
에러
비활성화
포커스 시 카운트 라벨
https://github.com/boostcampwm2023/web17_morak/assets/43867711/4c496138-af5a-4cb5-9523-201d83f2eb0d
비활성화 시 마우스 포인터
https://github.com/boostcampwm2023/web17_morak/assets/43867711/cb3ac2e4-52c4-4f38-91de-434a36347db1
- 코멘트로 남겨 놓음
- 0/16과 같은 current length의 경우 아직 작업하지 않았습니다. 추후 react-hook-form과 함께 사용될 때 props 추가 작업이 있을 수 있습니다.
- 라벨의 피그마 상 폰트 사이즈가 작아 9px → 12px로 작업했습니다.
- eslint의 react/require-default-props 룰을 Off 처리했습니다.
=> [Feat] Input 컴포넌트 구현

app/frontend/Dockerfile, app/frontend/docker-compose.yml, app/frontend/package.json
- Docker 를 이용하여 프로젝트 파일 복사 -> 의존성 설치 및 빌드 -> preview 서버 실행의 구조로 돌아가는 Dockerfile 작성
- [ O ] Docker와 Docker Compose를 이용하여 FE 서버를 띄움.  
[](http://soam2.iptime.org:9991) 참조
@ldhbenecia Dockerfile 및 docker-compose.yml 확인 부탁합니다.
=> [Feat] 프론트엔드 Docker 설정

app/frontend/src/components/commons/Label/index.css.ts, app/frontend/src/components/commons/Label/index.tsx
- #85 이슈 해결 이후 빌드 시 절대 경로 수정되지 않은 부분이 발견되어 수정했습니다.
X
X
=> [Hotfix] @styles 절대 경로 바뀌지 않은 부분 수정

.husky/pre-commit, app/frontend/package.json
- #103 
- husky 작업 시 staged가 아닌 파일에도 husky 적용되는 이슈 발생하여 pre-commit 명령 및 scripts를 수정했습니다.
- husky 파일을 루트 경로가 아닌 frontend 디렉토리만 둘 수 있는지 여부는 확인해 보도록 하겠습니다. (따라서 issue를 닫지 않음)
X
X
=> [Chore] husky 설정 파일 수정

app/frontend/src/components/commons/Popover/index.css.ts, app/frontend/src/components/commons/Popover/index.tsx, app/frontend/src/components/index.ts
- closed #59 
- 배경과 popover 컴포넌트 모두 흰색이라 상단 화살표가 잘 보이지 않아 그림자 효과를 조정했습니다.
- `app/frontend/.eslintrc.cjs`와 `packages/eslint-config/frontend.js`에서 작성한 eslint rule 설정이 중복되어서 `app/frontend/.eslintrc.cjs`에 작성한 규칙은 아예 삭제했습니다. `packages/eslint-config/frontend.js`에서만 작성하는 걸로.
=> [Feat] Popover 컴포넌트 구현

app/backend/src/auth/auth.controller.ts, app/backend/src/member/dto/member.dto.ts, app/backend/src/member/interface/user.interface.ts, app/backend/src/member/member.controller.ts, app/backend/src/member/member.service.ts
Swagger를 작성하여 문서화합니다.
클라이언트에게 반환해주는 Response를 Swagger에 문서화하지않아서 Response 값에 대한 Swagger를 작성하였습니다.
x
=> [Feat] Google OAuth, Member 정보 반환 Swagger

app/backend/src/auth/auth.controller.ts, package-lock.json
빠른 테스트를 위해 바로 PR을 올립니다.
Vault에 클라이언트/auth로 이동하는 환경변수를 설정하였고 그에 따라 코드에 getSecret을 사용하여 적용시켰습니다.
=> [Feat] OAuth Redirect URL Vault 적용

.github/workflows/ci-frontend.yml
- closed #118 
- 백엔드 CI/CD 구축 시 프론트엔드의 단순 typo error로 인하여 에러 해결에 소요된 시간이 많았습니다. 😂 경로 별칭을 수정함으로 인해 생긴 문제였는데, 프론트엔드 코드 리뷰 시 세부사항까지 리뷰할 수 없어 미처 체크하지 못해 발생한 문제였습니다. 이러한 문제를 해결하기 위해 'Front-end' 라벨과 함께 PR을 올릴 경우 프론트엔드 CI 파이프라인에 따라 빌드 가능 여부를 체크하여 문제를 예방합니다.
- 현재 test CI는 주석 처리한 상태인데, 테스트 코드가 추가되면 test code check CI도 활성화할 예정입니다.
개인 로컬 테스트 스크린샷입니다.
- 빌드가 실패할 경우 다음과 같이 failed 메시지가 뜹니다.
- 에러를 해결하고 빌드를 성공했다면 all checks have passed 메시지가 뜹니다.
=> [Feat] 프론트엔드 ci 파일 추가

app/frontend/src/constants/index.ts, app/frontend/src/constants/url.ts, app/frontend/src/services/morakAPI.ts
- 현재 배포된 웹 사이트의 경우 환경 변수 세팅이 되어 있지 않아 api 테스트를 할 수 없습니다.
- 프론트에서 vault 사용을 보류하고, 환경 변수 대신 API url을 상수로 관리하도록 변경합니다.

x
x
=> [Feat] API 주소 환경 변수 대신 상수로 관리

app/frontend/src/pages/Main/index.tsx
- 로그인 버튼 클릭 시 env 환경 변수 상수로 변경하는 부분 누락하여 버그 발생
x
x
=> [Bug] 로그인 페이지 이동 시 env 환경 변수 상수로 변경

app/frontend/src/pages/Main/index.tsx, app/frontend/src/services/morakAPI.ts
- access_token이 있을 경우 axios 헤더에 Authorization을 추가합니다.
- 메인 화면 버튼 렌더링을 전역 state로 하고 있었는데, 이를 쿠키 값 여부로 판단하도록 수정했습니다.
=> [Feat] 프론트엔드에서 로그인 사용자 판단

app/frontend/package.json, app/frontend/src/components/MogacoPost/index.tsx, app/frontend/src/hooks/index.ts, app/frontend/src/hooks/useUserInfo.ts, app/frontend/src/mocks/mogaco.ts, app/frontend/src/services/mogaco.ts, app/frontend/src/types/mogaco.ts, app/frontend/src/utils/cookies.ts, package-lock.json
- jwt-decode를 사용하여 액세스 토큰에서 유저 정보를 받아오는 로직을 임시로 구현하였습니다. (흠.. 이래도 되나 싶네요. 그래서 임시로만 사용해야 할 것 같다고 생각.)
- @LEEJW1953 글 작성 컴포넌트에서 로직 분리는 일부러 안 한 것도 있습니다. 추후 저 또는 누군가로 인해 수정될 예정입니다. 하핫~!
- 로컬에서 테스트를 해 보지 않아서 배포 후 테스트 필요합니다. 에러가 발생할 수도...
https://github.com/boostcampwm2023/web17_morak/assets/43867711/1e06ba3a-eefa-456c-94f3-fc2384890b5c
=> [Feat] 모각코 글 작성

app/frontend/src/components/MogacoPost/index.tsx, app/frontend/src/mocks/mogaco.ts
- 글 Post 요청 성공 시 status code를 200 > 201로 변경합니다.
=> [Fix] 글 post 성공 시 status code를 201로 변경

app/frontend/src/components/MogacoDetail/index.tsx
- 사용자 인증 실패 시 알럿 창과 함께 메인 페이지로 리다이렉션 시키던 코드를 제거합니다.
=> [Fix] 인증 실패 시 리다이렉션 코드 제거

app/frontend/src/components/MogacoDetail/DetailHeader.tsx, app/frontend/src/components/MogacoDetail/DetailHeaderButtons.tsx, app/frontend/src/components/MogacoDetail/index.tsx
- 사용자 인증 실패 시 기능 제한을 버튼으로만 표시하도록 변경하였습니다. (기존: 모각코 게시글 열람 불가)
=> [Fix] 사용자 미인증 시 제한을 버튼에만 적용하도록 변경

app/backend/src/member/member.controller.ts
member/me API에 인증 가드를 걸어서 액세스토큰을 검증합니다.
=> [Feat] me API 로그인 인증 가드 적용

app/backend/src/member/member.module.ts
=> [HotFix] member Moudle에 AuthModule 적용

app/backend/package.json, app/frontend/package.json, package-lock.json, packages/apitype/package.json
- 해당 모듈은 API 명세를 한번에 정의하기 위해 FE, BE에서 동시에 사용 가능한 API 타입 모듈입니다.
- 아직 BE의 DTO들이 전부 이전된 상태는 아니며, 일단 develop에 머지한 다음 수정할 계획입니다. 
@ldhbenecia mogaco 이름 명명에 대해 논의가 필요합니다.
@ttaerrim API 명세에 대해 논의가 필요합니다.
=> [Feat] API 공통 타입 모듈 구성

app/backend/src/groups/dto/groups.dto.ts, app/backend/src/mogaco/dto/create-mogaco.dto.ts, app/backend/src/mogaco/dto/response-mogaco.dto.ts, app/backend/src/mogaco/dto/response-participants.dto.ts, app/backend/src/mogaco/mogaco.controller.ts, app/backend/src/mogaco/mogaco.repository.ts, app/backend/src/mogaco/mogaco.service.ts, packages/apitype/dto/request/mogaco.ts, packages/apitype/dto/response/groups.ts, packages/apitype/dto/response/mogaco.ts, packages/apitype/dto/response/participant.ts, packages/apitype/dto/type.ts
- close #216 
request, response에 해당하는 bigint를 전부 string으로 dto를 변경합니다.
=> [Refactor] bigint 타입 string으로 변경

app/frontend/src/services/morakAPI.ts
- FE에서 요청을 보낼 때 쿠키가 전달되지 않는 버그를 수정하였습니다.
=> [Fix] Axios 설정에 'withCredentials' 옵션 추가

app/frontend/package.json, turbo.json
- turbo를 사용하기 위한 설정 PR입니다.
- turbo를 설치했음에도 불구하고 활용하고 있지는 않다는 피드백을 받아 설정해 보았습니다.
- 다음 커맨드는 다음과 같이 실행할 수 있습니다.
```diff
- npm run dev -w=frontend
+ turbo dev --filter frontend
- npm run start:dev -w=backend
+ turbo start:dev --filter backend
```
- 패키지 설치 커맨드는 사용하던 대로 사용합니다.
```
npm install <package> -w=frontend
```
- cache 전략을 내부적으로 사용하고 있기 때문에, 변경된 점 없이 같은 커맨드를 실행할 경우 속도가 빨라집니다. (이게 꿀인 것 같아요)<sup>[[1]](#ref1)</sup>
- app/* 내 package.json에 같은 커맨드가 있을 경우 해당하는 폴더의 커맨드가 모두 실행됩니다. <sup>[[2]](#ref2)</sup>
- `turbo lint`를 실행하는 경우 backend와 frontend의 lint scripts가 모두 실행됨
- 여러 scripts를 한꺼번에 실행할 수 있습니다. <sup>[[3]](#ref3)</sup>
```diff
- npm run lint -w=frontend
- npm run build -w=frontend
- npm run dev -w=frontend
+ turbo lint build dev --filter frontend
```
<a …
=> [Feat] turbo 설정 추가

app/frontend/package.json
- app/frontend의 package.json에 @morak/apitype 중복 선언이 되어 있어 코드 삭제
=> [Bug] @morak/apitype 중복 선언 해결

app/frontend/src/components/FieldLabel/index.css.ts, app/frontend/src/components/FieldLabel/index.tsx, app/frontend/src/components/Input/index.css.ts, app/frontend/src/components/Input/index.tsx, app/frontend/src/components/index.ts
- Input 컴포넌트에서 label 영역인 FieldLabel을 분리했습니다.
- #231 PR에서 FieldLabel만 사용하게 될 경우가 생겨 분리했습니다. (그룹 영역)
=> [Refactor] Input 컴포넌트에서 FieldLabel을 분리

app/frontend/src/pages/Calendar/CalendarView.css.ts, app/frontend/src/pages/Calendar/index.css.ts
=> [Design] 캘린더 크기 조정

app/frontend/src/pages/Calendar/CalendarView.css.ts, app/frontend/src/pages/Calendar/CalendarView.tsx
- 시간이 잘리지 않도록 스타일 조정
- 시간을 mm:ss 형식으로 나타냄
- 시간이 잘리지 않도록 스타일 조정
- 시간을 mm:ss 형식으로 나타냄
before 
after
=> [Desgin] 캘린더 이벤트 스타일 수정

app/frontend/src/components/Label/index.css.ts, app/frontend/src/components/Sidebar/Contents/Mogaco/TitleWrapper.tsx, app/frontend/src/components/Sidebar/Contents/Mogaco/index.css.ts
- ellipsis 설정
- 라벨 줄 바뀌지 않도록 수정
- 모각코 사이드바 제목 길 경우 디자인 수정했습니다.
before 
after
=> [Design] 모각코 사이드바 제목 디자인 조정

app/frontend/src/pages/MogacoPost/index.tsx
- 유저에게 필드가 제대로 작성되지 않았다는 것을 알리기 위한 목적으로 폼 유효성 검사가 통과하지 않았을 때는 버튼을 비활성화합니다.
- react hook form의 isValid 변수를 사용
https://github.com/boostcampwm2023/web17_morak/assets/43867711/04d42940-9df6-4b62-92cb-3616b4fc84f9
=> [Modify] 폼 유효성 검사 통과하지 않았을 경우 버튼을 비활성화 처리

app/backend/prisma/migrations/20231129172258_commit_cd906f7/migration.sql
=> [Fix] DB migration update

app/backend/src/chat/chat.gateway.ts, app/backend/src/chat/chat.module.ts, app/backend/src/chat/chat.service.ts, packages/morak-chat/package.json, packages/morak-chat/src/client/index.ts, packages/morak-chat/src/index.ts, packages/morak-chat/src/interface/index.ts, packages/morak-chat/src/interface/user.interface.ts, packages/morak-chat/src/server/decorator/auth-user.decorator.ts, packages/morak-chat/src/server/decorator/room.decorator.ts, packages/morak-chat/src/server/index.ts, packages/morak-chat/tsconfig.json
- 유저 인터페이스 내용 변경
- 인터페이스 종류 세분화
- 연결 url 변경
@js43o
=> [Feat] 채팅 2차 작업

app/backend/prisma/migrations/20231130060550_map/migration.sql, app/backend/prisma/migrations/20231130061623_map/migration.sql, app/backend/prisma/schema.prisma, app/backend/src/member/member.controller.spec.ts, app/backend/src/mogaco/dto/create-mogaco.dto.ts, app/backend/src/mogaco/dto/response-mogaco.dto.ts, app/backend/src/mogaco/mogaco.repository.ts, packages/apitype/dto/request/mogaco.ts, packages/apitype/dto/response/mogaco.ts
- close #252 
```json
{
"groupId": 1,
"title": "지도 확인",
"contents": "지도 확인을 위한 데이터",
"date": "2023-11-25T12:00:00.000Z",
"latitude": 12.1111111,
"longitude": 127.1111111,
"maxHumanCount": 5,
"status": "모집 중",
"address": "테스트 주소"
}
```
```json
{
"id": "1",
"groupId": "1",
"memberId": "1",
"title": "지도 확인",
"contents": "지도 확인을 위한 데이터",
"date": "2023-11-25T12:00:00.000Z",
"maxHumanCount": 5,
"address": "테스트 주소",
"latitude": "12.1111111",
"longitude": "127.1111111",
"status": "모집 중",
"createdAt": "2023-11-30T06:22:21.529Z",
"updatedAt": "2023-11-30T06:22:21.529Z",
"deletedAt": null,
"member": {
"id": "1",
"providerId": "117187214221556274884",
"email": "bcwm.morak@gmail.com",
"nickname": "morak morak",
"profilePicture": "https://lh3.googleusercontent.com/a/ACg8ocKej7-OYc7vwz5Xu8Tss37yWKC5vEVMe …
```
=> [Feat] 지도 API 구현, Dto 추가

packages/morak-chat/src/client/index.ts, packages/morak-chat/src/interface/message.interface.ts, packages/morak-chat/src/interface/user.interface.ts, packages/morak-chat/src/server/decorator/message.decorator.ts
- 모듈 DTO 수정
- 모듈 클라이언트 로직 변경
@js43o
=> [fix] 채팅 공통 모듈 버그 픽스

app/backend/src/member/member.controller.spec.ts, app/backend/src/member/member.controller.ts
=> [Test] member 컨트롤러 테스트 코드 작성 

app/frontend/index.html, app/frontend/src/components/Input/index.tsx, app/frontend/src/components/Modal/MapModal.css.ts, app/frontend/src/components/Modal/MapModal.tsx, app/frontend/src/components/index.ts, app/frontend/src/pages/MogacoPost/Controller/PostAddress.tsx, app/frontend/src/types/global.d.ts
- #261 
- 폼 작성 시 지도로 장소를 선택할 수 있도록 하기 위한 맵 모달 생성
- Input 컴포넌트에 list 속성 추가
- 현재 인풋 컴포넌트에 props로 넘어가는 값이 많아지고 있습니다. 추후 리팩토링 예정 
=> [Feat] 맵 모달 추가

app/frontend/src/pages/MogacoPost/Controller/PostGroupId.tsx, app/frontend/src/pages/MogacoPost/Controller/group.css.ts
- 그룹 필드 라벨 추가
- 속한 그룹 없는 경우 안내 문구 추가 (추후 그룹 추가할 수 있는 페이지로 이동하는 버튼 추가 예정)
=> [Design] 글 작성/수정 페이지 그룹 예외 사항 처리

app/backend/src/groups/dto/create-groups.dto.ts, app/backend/src/groups/groups.controller.ts, app/backend/src/groups/groups.repository.ts, app/backend/src/groups/groups.service.ts
- close #269 
그룹 생성 기능을 구현합니다.
피그마를 확인하면 그룹장에 대해 왕관 표시를 해두었는데
그룹장에 대한 기능 구현은 포함하지않았습니다.
x
=> [Feat] 그룹 생성 기능 구현

app/frontend/src/components/Modal/MapModal/index.tsx, app/frontend/src/pages/MogacoPost/Controller/PostAddress.tsx, app/frontend/src/pages/MogacoPost/index.tsx
- #261 
- from [c9f02b1](https://github.com/boostcampwm2023/web17_morak/pull/265/commits/c9f02b1fa1799b1ef03889adf4200f01726d98d3)
- 이 PR 머지되면 develop 브랜치로 머지하겠습니다.
=> [Feat] 글 POST 요청 시 위도 경도 추가

app/backend/package.json, app/backend/src/member/member.controller.spec.ts, app/backend/src/member/member.controller.ts, app/backend/src/member/member.service.spec.ts, app/backend/src/member/member.service.ts, package-lock.json
- close #274 
- close #278 
[Path Alios 설정 기록](https://ttaerrim.notion.site/Jest-path-alios-433965335b5845878257813e3e733cac?pvs=4)
=> [Test] Member API Unit Test, path alios 설정

app/frontend/src/components/Modal/MapModal/useMap.ts, app/frontend/src/types/global.d.ts
=> [Chore] 맵 모달 줌 컨트롤 바 숨김 처리

app/frontend/src/pages/Groups/index.css.ts, app/frontend/src/pages/Groups/index.tsx, app/frontend/src/queries/group.ts, app/frontend/src/services/group.ts
=> [Modify] 그룹 페이지 API fetch 하여 보여 주기

app/frontend/src/types/global.d.ts
- featuer/socket-io <- develop 머지 누락 내용 추가하겠습니다.
- 전에 리뷰 받았던 내용입니다.
=> [hotfix] 머지 누락 내용 추가

app/backend/package.json, app/backend/src/groups/groups.controller.spec.ts, app/backend/src/groups/groups.repository.spec.ts, app/backend/src/groups/groups.service.spec.ts, app/backend/src/member/member.controller.spec.ts, app/backend/src/member/member.service.spec.ts
=> [Test] Groups API 단위 테스트

.github/workflows/deploy-frontend.yml, app/backend/Dockerfile
- turbo 적용으로 인해 Dockerfile에서 환경 변수 적용에 대해 문제 있던 부분 수정
- Dockerfile 나누면서 action 돌아가지 않는 문제 수정
=> [bug] .env 없을 때 dokckerfile 수정 및 fe 배포 action 수정

.github/workflows/ci-frontend.yml, app/frontend/package.json, app/frontend/src/utils/createRangeArray.test.ts, app/frontend/src/utils/get10UnitRange.test.ts, app/frontend/src/utils/get10UnitRange.ts, package-lock.json
- 페이지네이션 관련 유틸 함수 테스트 케이스 추가
- CI/CD test 활성화
=> [Test] Pagination에서 쓰이는 유틸 함수 테스트 케이스 추가

app/frontend/src/components/Group/hooks/useGroupJoinLeave.tsx, app/frontend/src/components/Group/hooks/useGroupModal.tsx, app/frontend/src/components/Group/index.tsx, app/frontend/src/pages/Groups/index.tsx, app/frontend/src/queries/hooks/group.ts, app/frontend/src/services/group.ts
- #296 
- 참여하기 버튼을 눌렀을 때 보이는 팝업에 contents가 포함되어 있는데, contents의 길이에 따라 팝업 width가 자동 조절되어 팝업 디자인을 변경하는 작업을 다른 PR에서 할 예정입니다. <sup>[[1]](#ref1)</sup>
- 참여하기 버튼을 눌렀을 경우, 현재 참여한 그룹이 있다면 그 그룹을 탈퇴시키는 로직이 포함되어 있습니다. 추후 기획에 따라 변경될 수도 있음.
<a id='ref1'></a>
https://github.com/boostcampwm2023/web17_morak/assets/43867711/03d57283-5c01-4da4-938a-09a4586a02d8
=> [Modify] 그룹 나가기/참여하기 기능 추가

app/frontend/src/pages/MogacoPost/Controller/PostAddress.tsx, app/frontend/src/pages/MogacoPost/index.tsx
- closed #309 
- 버그는 이슈 확인 부탁드립니다.
- react-hook-form의 setValue 메소드 사용 시 `{ shouldValidate: true }` 옵션을 함께 사용하여 직접 form 값을 변경할 경우 form 상태에 대한 업데이트를 활성화시킵니다.
- setGroup 함수를 useCallback으로 감싸 사용하여 무한 렌더링 현상을 해결했습니다.
https://github.com/boostcampwm2023/web17_morak/assets/43867711/5fc6d29f-142a-40e6-b02e-1b5e2b08b4bd
=> [Bug] 폼 작성 페이지에서 작성 버튼 활성화되지 않는 버그 

app/frontend/src/services/mogaco.ts
=> [Modify] 글 수정 METHOD patch에서 put으로 변경

app/frontend/src/components/Layout/index.css.ts, app/frontend/src/pages/Calendar/CalendarView.css.ts, app/frontend/src/pages/Mogaco/index.css.ts, app/frontend/src/pages/Profile/index.css.ts
=> [Design] 레이아웃 수정

app/frontend/index.html
- `index.html`의 파비콘 경로로 인해 아래와 같은 경고가 발생합니다.
- `/public/morak.ico` → `/morak.ico` 로 경로를 수정하였습니다.
=> [Fix] 파비콘 경로 수정

app/frontend/src/assets/icons/location.svg, app/frontend/src/components/Map/Marker.tsx, app/frontend/src/components/Map/MyLocation.tsx, app/frontend/src/components/Map/index.css.ts, app/frontend/src/components/Map/index.tsx, app/frontend/src/hooks/useMap.ts, app/frontend/src/pages/Map/index.css.ts, app/frontend/src/pages/Map/index.tsx, app/frontend/src/utils/index.ts, app/frontend/src/utils/reactElementToString.ts
- close #326 
- 지도의 모각코 마커에 날짜, 시간을 표시합니다.
- 현 위치 버튼을 추가합니다.
- `location.svg` 파일은 #325 머지 이후 이동할 예정입니다.
- 마커 라벨 디자인 피드백 받습니다.
- 수정된 마커<sup>[[1]](#ref1)</sup>
https://github.com/boostcampwm2023/web17_morak/assets/110762136/882aed0c-b601-460e-88d3-f9995f12672e
<a id='ref1'></a>
=> [Feature] 지도 마커에 날짜, 시간 표시, 내 위치 버튼 추가

app/backend/src/mogaco-boards/dto/response-mogaco.dto.ts, app/backend/src/mogaco-boards/mogaco-boards.repository.ts, packages/apitype/dto/response/mogaco.ts
=> [Refacotr] 특정 게시물 조회 시 groupId 추가 반환

app/frontend/src/pages/MogacoPost/Controller/PostAddress.tsx, app/frontend/src/pages/MogacoPost/index.tsx
- #336 
- latitude, longitude, groupId 누락 해결
- isDirty 필드를 버튼 disabled의 값으로 추가 사용하여, 글이 변경되었을 경우에만 수정 버튼을 활성화
- 이에 따라 setValue 메소드에 `shouldDirty: true` 옵션 추가 
https://github.com/boostcampwm2023/web17_morak/assets/43867711/e721175e-62a9-4bb6-8025-d96695f00309
=> [Bug] 글 수정 버그 해결

app/frontend/src/components/Modal/Footer.tsx, app/frontend/src/components/Modal/index.css.ts, app/frontend/src/components/Modal/index.tsx
- closed #342 
- Modal은 onClickConfirm 옵셔널로 되어 있는데 Footer 변경되어 있지 않아서 수정
before
after
=> [Design] 모달 디자인 수정

.github/workflows/deploy-backend.yml, .github/workflows/deploy-frontend.yml, app/backend/src/chat/chat.gateway.ts, app/backend/src/chat/chat.repository.ts, app/frontend/Dockerfile.product, app/frontend/src/components/Sidebar/Contents/Chatting/index.tsx, app/frontend/src/constants/url.ts, docker-compose.yml, nginx.conf.template, packages/morak-chat/src/client/index.ts, packages/morak-chat/src/server/decorator/message.decorator.ts, packages/morak-chat/src/server/decorator/room.decorator.ts, packages/morak-chat/src/server/decorator/user.decorator.ts, turbo.json
=> [fix] 빌드 파이프라인 변경

app/backend/src/chat/chat.guard.ts, app/backend/src/chat/chat.repository.ts, app/backend/src/chat/chat.service.ts
- Participant 테이블 컬럼 명 에러로 인한 컴파일 오류 해결
=> [fix] participant 테이블 컬럼 명 에러

app/frontend/src/components/MogacoItem/index.css.ts, app/frontend/src/components/MogacoItem/index.tsx
폰트 크기 변경, 아이콘 크기 변경
- close #335 
- 모각코 아이템 UI를 수정하였습니다.
- 전
- 후
=> [Design] 모각코 아이템 UI 수정

README.md
=> [Docs] README에 로고 추가

app/frontend/src/components/Modal/MapModal/index.css.ts
- #340 
- 모바일 뷰에서 검색 영역과 지도가 상하로 위치하도록 변경했습니다.
- 검색 결과를 보여 주는 ul를 position: absolute로 변경했습니다.
- 모바일에서는 검색 후 검색 영역이 지도를 약간 가리나, 디자인에 대한 고민도 함께 포함되어 있어... 이후 처리하도록 하겠습니다.
https://github.com/boostcampwm2023/web17_morak/assets/43867711/fc29110f-3369-4cd5-bb38-ced81e209fd8
=> [Design] 맵 모달 반응형

app/frontend/src/pages/MogacoPost/Controller/PostMember.tsx
- 모각코 수정 페이지 이동 시 아래와 같은 에러메시지가 발생합니다,
- 공식 문서의 [이 부분](https://react.dev/reference/react-dom/components/input#im-getting-an-error-a-component-is-changing-an-uncontrolled-input-to-be-controlled)과 [이 부분](https://react.dev/reference/react-dom/components/input#providing-an-initial-value-for-an-input)을 참고하였습니다.
- `controlled component`의 경우 `value` 속성으로 `state variable`을 사용하고, `onChange={()=>{setState()}}`등의 핸들러로 값을 변경합니다.
- 그렇지 않은 `uncontrolled component`의 기본값을 지정해주기 위해서는 `value` 대신 `defaultValue` 속성을 사용해야 합니다.
- 작성자 input의 `value` 속성을 `defaultValue`로 수정하였습니다.
=> [Fix] 모각코 수정 페이지 작성자 input 기본값 속성 defaultValue로 수정

app/backend/src/chat/chat.gateway.ts
=> [Feat] Chat Logger 설정 및 init 로그 설정

app/frontend/src/components/Group/index.tsx, app/frontend/src/pages/Profile/MyGroup/index.tsx
- closed #378 
- 마이페이지에서 사용하는 그룹 컴포넌트에 id가 누락되어 있어 id 전달하도록 수정
- 그룹 컴포넌트에서 현재 사용하지 않는 인원 수, 그룹 코드 부분 주석 처리
https://github.com/boostcampwm2023/web17_morak/assets/43867711/dc80087d-cfef-4c25-9c3b-8640b8aa6a05
=> [Bug] 마이페이지 내가 속한 그룹에서 나가기 작동하지 않음

app/frontend/src/pages/MogacoPost/index.tsx
- closed #377 
- defaultValue의 maxHumanCount: 0를 삭제
=> [Bug] 글 작성 시  최대 인원 수 필드가 비어 있도록 defaultValue 삭제

app/frontend/src/pages/Mogaco/EmptyPage.css.ts, app/frontend/src/pages/Mogaco/EmptyPage.tsx, app/frontend/src/pages/Mogaco/MogacoList.tsx, app/frontend/src/pages/Mogaco/MogacoListHeader.tsx, app/frontend/src/pages/Mogaco/NoGroupPage.tsx
- closed #401 
- 그룹 없을 경우 그룹 없음 메시지 표시
- NoGroup 컴포넌트 추가
=> [Modify] 모각코 리스트 페이지에서 그룹 없을 경우 개선

app/frontend/src/hooks/useRouter.tsx, app/frontend/src/pages/NotFound/index.css.ts, app/frontend/src/pages/NotFound/index.tsx, app/frontend/src/pages/index.ts
=> [Feat] 404 페이지 추가

app/frontend/src/pages/Main/index.css.ts
- close #407
- 메인 페이지 모바일에서 불필요한 스크롤이 발생하여 반응형 height를 수정하였습니다.
=> [Design] 메인페이지 반응형 height 수정

app/frontend/src/components/Group/index.css.ts, app/frontend/src/components/Group/index.tsx
- closed #408 
- 그룹 컴포넌트에서 모바일/데스크톱 그룹 버튼을 분리해 놓은 줄 모르고 주석 처리했다가 생긴 이슈
- 그룹 컴포넌트 디자인 개선했습니다.
- 같은 기능을 하는 버튼을 두 개 두고 반응형으로 분기 처리하는 것보다 디자인 개선을 하는 것이 나을 것 같아서 변경했습니다. 
=> [Bug] 그룹 컴포넌트 버그 해결 및 디자인 수정

README.md
- README 기능 설명 추가
- https://github.com/boostcampwm2023/web17_morak/pull/424/files?short_path=b335630#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5
- 여기서 확인 가능
- 추가하고 싶은 것, 혹은 변경하고 싶은 것, 제안.. 등등 코멘트로 부탁드립니다 
=> [Docs] README 기능 설명 추가

app/frontend/cypress.config.ts, app/frontend/cypress/e2e/spec.cy.ts, app/frontend/cypress/fixtures/example.json, app/frontend/cypress/support/commands.ts, app/frontend/cypress/support/e2e.ts, app/frontend/package.json, package-lock.json, turbo.json
=> [Feat] cypress 설치

app/frontend/package.json, package-lock.json, packages/morak-ui/.eslintrc.cjs, packages/morak-ui/package.json, packages/morak-ui/src/index.ts, packages/morak-ui/tsconfig.json
- @morak/ui 패키지 추가
- 기본적인 구조와 configuration 파일 추가
=> [Refactor] @morak/ui 패키지 추가

app/frontend/package.json, app/frontend/src/pages/Main/index.tsx, package-lock.json, packages/morak-ui/.eslintrc.cjs, packages/morak-ui/package.json, packages/morak-ui/src/components/Button/index.css.ts, packages/morak-ui/src/components/Button/index.tsx, packages/morak-ui/src/index.ts, packages/morak-ui/src/styles/font.css.ts, packages/morak-ui/src/styles/index.ts, packages/morak-ui/src/styles/reset.css.ts, packages/morak-ui/src/styles/theme.css.ts, packages/morak-ui/tsconfig.json
- 메인 페이지에서 Button 컴포넌트 @morak/ui에 옮긴 버튼 사용해 보기
테스트 통과 오나료
=> [Refactor] 버튼 컴포넌트 @morak/ui로 사용

app/backend/package.json, package-lock.json
- close #458 
삭제당해서 사라졌던 필수 모듈을 재설치합니다.
=> 📦️ nestjs platform-express install

app/frontend/src/App.tsx
=> [Bug] App.tsx의 CookieProvider 삭제

app/backend/src/main.ts
=> [Refactor] main.ts 현재 환경 콘솔로그 제거

.github/CODEOWNERS, packages/morak-ui/.prettierrc, packages/morak-ui/package.json, packages/morak-ui/src/components/Button/index.tsx, packages/morak-ui/src/components/Input/Textarea.tsx, packages/morak-ui/src/components/Input/index.tsx
=> [Refactor] Morak UI에 prettier 추가

app/frontend/src/components/Map/Marker.tsx, app/frontend/src/components/Map/index.css.ts, app/frontend/src/hooks/useMap.ts
- 지도 초기 좌표 추가
- 마커 이미지 경로 수정
- before
- after
=> [Fix] 지도 초기 좌표 추가, 마커 이미지 경로 수정

app/backend/src/mogaco-boards/mogaco-boards.repository.ts
=> [Refactor] 모각코 리스트 생성일 내림차순으로 조회 구현

app/frontend/src/components/MogacoItem/index.tsx, app/frontend/src/pages/MogacoDetail/DetailInfo.tsx, app/frontend/src/pages/MogacoPost/index.tsx
=> [Bug] HH:MM > HH:mm 찾아서 수정

app/backend/test/app.e2e-spec.ts, app/backend/test/jest-e2e.json, app/backend/tsconfig.json
=> [Test] e2e 테스트 세팅 및 app e2e 테스트

app/backend/src/groups/dto/groups.dto.ts, app/backend/src/mogaco-boards/mogaco-boards.repository.ts
- close #523 
그룹 스키마 변경으로 인해 dto를 추가적으로 수정해야하였습니다.
모각코 게시판 부분에서 특정 모각코를 불러올 때 그룹 부분에서 추가적으로 그룹장과, 그룹 타입의 정수값을 반환합니다.
=> [Refactor] Group 스키마 변경으로 인한 코드 수정

app/frontend/src/components/Modal/MapModal/index.tsx
- closed #521 
- 주소 값을 가져오는 과정에서 `const fullAddress = address.newAddressList.newAddress[0].fullAddressRoad;`의 `fullAddressRoad` 속성이 없는 경우가 있어, 옵셔널 체이닝으로 해결
bug issue와 똑같이 입력했을 경우 버그 발생하지 않음
https://github.com/boostcampwm2023/web17_morak/assets/43867711/2c45e654-2b45-4d21-b7d3-1f7815e7d36b
=> [Bug] 장소 모달에서 장소 검색 시 undefined 에러 발생하는 버그
