boostcampwm2023/web17_morak

app/frontend/tsconfig.json
app/frontend/vite.config.ts

close #69 
- index.* 파일을 import 할 경우 파일명을 생략하고 해당 파일이 존재하는 디렉토리명으로 불러올 수 있도록 설정을 변경했습니다.
- 웬만한 경우의 자동 완성까지 확인했으나 예외가 있을 수 있습니다! 발견하시면 말씀해 주세요.
- 예외적으로 `src/App.tsx` 파일에서는 원인을 알 수 없지만 자동 완성으로 불러오는 파일의 이름이 `index.*`가 아닐 경우 확장자가 붙은 채로 import 됩니다. (다른 곳에서 불러올 때에는 확장자가 정상적으로 제외됩니다)

[Feat] index.* 파일을 디렉토리명으로 import 할 수 있도록 변경

---

packages/eslint-config/frontend.js

- close #61 
- 아래 코드와 같은 `unassigned import`의 경우 순서가 맞지 않으면 경고가 발생하지만, `lint:fix` 명령어나 저장시 자동 lint 등으로 해결되지 않아서 직접 순서를 수정해야 할 것 같습니다
- 참고 : [eslint-plugin-import](https://github.com/import-js/eslint-plugin-import/blob/HEAD/docs/rules/order.md#warnonunassignedimports-truefalse)
```js
import reactLogo from '@assets/react.svg';
import { Header } from '@components/commons/Header';
import '@styles/reset.css'; // unassigned import
```

[Feat] ESLint import 순서 설정

---

app/backend/prisma/migrations/20231119084220_init/migration.sql
app/backend/prisma/schema.prisma
app/backend/src/auth/auth.controller.ts
app/backend/src/auth/auth.repository.ts
app/backend/src/auth/auth.service.ts
app/backend/src/auth/dto/user.dto.ts
app/backend/src/auth/types/index.ts
app/backend/src/auth/types/user.interface.ts

- close #93 
Jwt 토큰에 유저 정보를 추가합니다.
클라이언트에 사용자 정보를 전달하기 위한 Get API에 기능을 추가하였습니다.
원래 provider_id만 넘겨주는 형식이었지만 기획과 클라이언트에 필요한 정보가 더 필요하여 추가하였습니다.
x

[Feat] Jwt 토큰 유저정보 추가

---

app/backend/src/auth/auth.controller.ts
app/backend/src/auth/interface/payload.interface.ts

공수가 너무 많이 들어갈 것으로 예상되어 httponly를 false로 변경하여 클라이언트에서 쿠키에 접근할 수 있도록 합니다.
추후에 여유가 생긴다면 보안에 신경쓰면서 보수를 할 예정입니다.
httponly=false

[Feat] Google OAuth 수정 사항

---

app/frontend/src/components/commons/Input/Textarea.css.ts
app/frontend/src/components/commons/Input/Textarea.tsx
app/frontend/src/components/commons/Input/index.css.ts
app/frontend/src/components/commons/Input/index.tsx
app/frontend/src/components/index.ts

- Input 디자인과 같은 Textarea 컴포넌트 생성
- index.css.ts 파일을 Textarea.css.ts에서 그대로 Export 했습니다. 추가적으로 스타일이 필요한 부분은 상속하여 사용할 수 있도록 했습니다.
- Input/Textarea의 제목(라벨) 필드를 옵셔널로 변경하고, 영역은 그대로 차지하도록 두었습니다. focus 되었을 때 글자 수를 표시하는 부분이 생겨 height가 변경되기 때문입니다.
- closed #49 

[Feat] Textarea 퍼블리싱

---

app/frontend/src/components/commons/Button/index.tsx
app/frontend/src/components/commons/Input/index.css.ts
app/frontend/src/components/commons/Input/index.tsx
app/frontend/src/components/commons/Modal/Footer.tsx
app/frontend/src/components/commons/Modal/InputModal.tsx
app/frontend/src/components/commons/Modal/index.css.ts
app/frontend/src/components/commons/Modal/index.tsx
app/frontend/src/styles/reset.css.ts

close #87
- 재사용 가능한 모달 컴포넌트를 만듭니다.
https://github.com/boostcampwm2023/web17_morak/assets/50646827/1953e841-b971-4f7b-a5b3-add6b52e5618
- Modal 컴포넌트는 내부에서 `React.ref` 객체를 사용합니다.
```tsx
function App() {
const ref = useRef<HTMLDialogElement>(null); // ref 객체를 Dialog 타입으로 선언
const openModal = () => ref.current?.showModal(); // 모달을 열 때에는 .showModal() 메소드 사용
return (
<>
<Modal dialogRef={ref} buttonType="double" title="제목" onClickConfirm={...} /> // ref를 props로 전달
</>
);
}
```
- 아직 모달의 상세한 동작 방식은 생각하지 않고 UI를 위주로 구현한 상태입니다. 이후 구현 과정에 따라 일부 정의가 달라질 수 있습니다.

[Feat] Modal 컴포넌트 구현

---

app/frontend/src/components/commons/Header/index.css.ts
app/frontend/src/components/commons/Layout/index.css.ts
app/frontend/src/components/commons/Layout/index.tsx

- close #62
- 헤더 상단 고정 및 최상단 배치
https://github.com/boostcampwm2023/web17_morak/assets/110762136/706ada34-2b64-45c1-97bc-f5158693aa3a

[Feat] 헤더 상단 고정 및 z-index 수정

---

app/frontend/src/components/commons/Layout/index.css.ts

- closed #126 
- 프론트엔드 레이아웃 통일성을 맞추기 위해 Layout에 maxWidth 설정을 추가합니다.
- 1200px 이하 레이아웃을 위해 양옆 패딩을 추가했습니다. <sup>[[1]](#ref1)</sup>
<a id="ref1"></a>
https://github.com/boostcampwm2023/web17_morak/assets/43867711/14c391ef-d9cd-4e3e-9db5-3a94fcae7cac

[Design] layout 컴포넌트 maxWidth 설정

---

app/frontend/src/components/commons/Sidebar/index.css.ts
app/frontend/src/styles/reset.css.ts

- Sidebar 컴포넌트의 위치가 고정되지 않는 버그를 수정했습니다.
- Sidebar 컴포넌트에 `position: 'fixed'` 속성 할당, 이후 위치 조정
- reset.css.ts에서 html, body, #root 요소에 `minHeight: '100vh'` 속성 추가
https://github.com/boostcampwm2023/web17_morak/assets/50646827/875a0d98-2470-4974-9651-309f0081567b
- 없음

[Fix] Sidebar 컴포넌트 위치 관련 버그 수정

---

app/frontend/package.json

- vite의 preview, dev의 명령에서 --host를 지정하지 않으면 localhost로만 떠서 외부에서 페이지에 접근이 불가한 문제 해결
@ttaerrim 확인 부탁드립니다.

[bug] preivew 명령이 배포 서버에서 정상적으로 작동하지 않는 문제 해결

---

app/frontend/src/components/commons/Layout/index.css.ts
app/frontend/src/pages/Main/index.css.ts

- #126 
- 현재 디자인은 pc 버전에서 헤더와 본문 사이의 간격이 일정하게 설정되어 있습니다. 이를 각각의 페이지 컴포넌트에서 디자인하지 않고 공통적으로 사용할 수 있도록 layout의 스타일을 조정했습니다.
before 
after

[Design] layout에 기본 패딩 값을 추가

---

app/frontend/package.json
app/frontend/src/components/Mogaco/MogacoList.css.ts
app/frontend/src/components/Mogaco/MogacoList.tsx
app/frontend/src/components/Mogaco/MogacoListHeader.css.ts
app/frontend/src/components/Mogaco/MogacoListHeader.tsx
app/frontend/src/components/Mogaco/index.css.ts
app/frontend/src/components/Mogaco/index.tsx
app/frontend/src/components/commons/MogacoItem/index.css.ts
app/frontend/src/components/commons/MogacoItem/index.tsx
app/frontend/src/components/index.ts
app/frontend/src/hooks/useRouter.tsx
app/frontend/src/pages/Mogaco/index.tsx
app/frontend/src/pages/index.ts
app/frontend/src/types/index.ts
app/frontend/src/types/mogaco.ts
package-lock.json

- closed #111 
- 피그마 기준 리스트 뷰 내부의 컴포넌트 크기는 735px로 설정되어 있습니다. 735라는 숫자가 너무 애매하기도 하고, 맥스로 맞춰 놓은 1200px에 꽉 차게 작업할 경우에는 헤더보다 내용 영역이 길어져 미관상 별로였습니다. 800px로 맞추어 작업했습니다.
- 피그마
- 1200px로 설정할 경우
- 모각코 아이템 컴포넌트의 스타일을 수정했습니다. 
- width가 고정값으로 되어 있어 이 부분을 수정하고, 화면이나 컨테이너의 width에 맞게 유동적으로 크기를 차지하도록 수정했습니다.
- 이 과정에서 `@vanilla-extract/css-utils` 패키지를 설치했었는데, 현재는 calc를 사용한 코드는 없으나 추후 사용을 위해 삭제하지는 않았습니다.
- MogacoItem에서 사용된 MogacoProps를 공통 타입으로 분리했습니다. 백엔드의 변수명과 맞추기 위해 변경할 경우, 서로 이야기하면서 작업해야 할 것 같습니다.

[Design] 모각코 리스트 뷰 퍼블리싱

---

app/frontend/src/components/Mogaco/MogacoList.tsx
app/frontend/src/components/Mogaco/MogacoListHeader.tsx
app/frontend/src/components/Mogaco/index.css.ts
app/frontend/src/components/commons/MogacoItem/index.tsx
app/frontend/src/constants/index.ts
app/frontend/src/constants/path.ts
app/frontend/src/mocks/handlers.ts
app/frontend/src/mocks/mogacos.ts
app/frontend/src/queries/index.ts
app/frontend/src/queries/mogaco.ts
app/frontend/src/services/index.ts
app/frontend/src/services/mogaco.ts
app/frontend/src/services/morakAPI.ts
app/frontend/src/types/mogaco.ts

- closed #121 
- React Query의 쿼리 키를 다룰 때 편리한 `@lukemorales/query-key-factory`를 사용했습니다.
사용하지 않는다면 다음과 같이 상수로 키를 관리할 수 있습니다. <sup>[[1]](#ref1)</sup>
```typescript
const mogacoKeys = {
all: ['mogaco'] as const,
lists: () => [...mogacoKeys.all, 'list'] as const,
list: (filters: string) => [...mogacoKeys.lists(), { filters }] as const,
details: () => [...mogacoKeys.all, 'detail'] as const,
detail: (id: number) => [...mogacoKeys.details(), id] as const,
}
```
`query-key-factory` 라이브러리는 유사한 형식으로 키를 생성해 주고, 이를 queryFn과도 연결하여 사용할 수 있어 편리합니다. 
```typescript
import { createQueryKeys } from '@lukemorales/query-key-factory';
import { mogaco } from '@/services';
export const mogacoKeys = createQueryKeys('mogaco', {
list: (filters?: { filters: { page: number } }) => ({
queryKey: [{ filters }],
queryFn: …
```

[Feat] 모각코 리스트 페이지 API 연동 및 리액트 쿼리 사용

---

app/backend/src/member/dto/member.dto.ts
app/backend/src/member/member.controller.ts
app/backend/src/mogaco/dto/create-mogaco.dto.ts
app/backend/src/mogaco/dto/mogaco.dto.ts
app/backend/src/mogaco/dto/response-mogaco.dto.ts
app/backend/src/mogaco/dto/response-participants.dto.ts
app/backend/src/mogaco/mogaco.controller.ts
app/backend/src/mogaco/mogaco.repository.ts
app/backend/src/mogaco/mogaco.service.ts

- close #142 
모각코에 다른 사용자들이 참가, 참가 취소, 참가자 확인하는 API를 작성합니다.
[스크린샷 기록소](https://ttaerrim.notion.site/381cd2ee87474cc090eac91309abf963?pvs=4)
현재 Swagger 설정 부분 코드가 상당히 더럽습니다.
1차원적으로 깎지 않고 바로 작성했습니다.
chatGPT로 한번 깎아보려고 했는데 코드 바꾸고 swagger를 본 결과 많이 달라져서 Reset Hard 처리하였습니다..
우선 swagger를 짜는데 생각보다 체력과 안구에 힘이 드는 관계로 프로젝트 마무리 즈음에 코드 정리를 할 때 시도해보면 좋을 것 같습니다.

[Feat] 모각코 참가자 관련 로직 구현 및 Swagger 설정

---

app/frontend/src/components/MogacoPost/MogacoPostTitle.tsx
app/frontend/src/components/MogacoPost/index.css.ts
app/frontend/src/components/MogacoPost/index.tsx
app/frontend/src/components/commons/Input/Textarea.tsx
app/frontend/src/components/commons/Input/index.tsx
app/frontend/src/constants/MogacoPost.ts
app/frontend/src/constants/index.ts
app/frontend/src/types/mogaco.ts

- #122 
- react hook form을 사용한 모각코 게시글 작성 폼 유효성 검사
- 폼에 사용할 메시지들 상수파일로 분리
https://github.com/boostcampwm2023/web17_morak/assets/110762136/b6e45111-163b-42ed-ba13-317453aa470e

[Feat] 모각코 게시글 작성 폼 유효성 검사

---

app/frontend/src/components/Mogaco/MogacoList.tsx
app/frontend/src/components/MogacoDetail/DetailHeader.tsx
app/frontend/src/components/MogacoDetail/DetailHeaderButtons.tsx
app/frontend/src/components/MogacoDetail/DetailInfo.tsx
app/frontend/src/components/MogacoDetail/index.css.ts
app/frontend/src/components/MogacoDetail/index.tsx
app/frontend/src/components/commons/MogacoItem/index.tsx
app/frontend/src/mocks/members.ts
app/frontend/src/mocks/mogaco.ts
app/frontend/src/pages/MogacoDetail/index.tsx
app/frontend/src/services/mogaco.ts
app/frontend/src/types/mogaco.ts

- close #149 
- 현재 사용자의 상태는 jotai를 통한 전역 상태에 있다고 가정했습니다.
- 참석하기/참석 취소 기능을 위해 mock 데이터를 객체로 분리했습니다.
- 위 두 기능에 대한 API 호출 후 리렌더링되지 않는 상태입니다. (결과를 확인하려면 해당 페이지를 직접 다시 불러와야 합니다, (나갔다 들어오기))
- `/mogaco/:id/participants` API 분리 반영했습니다.

[Feat] 모각코 상세 게시글 페이지 API 일부 구현

---

app/frontend/src/components/Mogaco/MogacoList.tsx
app/frontend/src/components/MogacoDetail/DetailContents.tsx
app/frontend/src/components/MogacoDetail/DetailHeader.tsx
app/frontend/src/components/MogacoDetail/DetailHeaderButtons.tsx
app/frontend/src/components/MogacoDetail/DetailInfo.tsx
app/frontend/src/components/MogacoDetail/index.tsx
app/frontend/src/components/commons/MogacoItem/index.tsx
app/frontend/src/main.tsx
app/frontend/src/mocks/members.ts
app/frontend/src/mocks/mogaco.ts
app/frontend/src/pages/MogacoDetail/index.tsx
app/frontend/src/queries/hooks/mogaco.ts
app/frontend/src/queries/index.ts
app/frontend/src/queries/member.ts
app/frontend/src/queries/mogaco.ts
app/frontend/src/services/member.ts
app/frontend/src/services/mogaco.ts
app/frontend/src/stores/user.ts
app/frontend/src/types/index.ts
app/frontend/src/types/member.ts
app/frontend/src/types/mogaco.ts

- #154
- #155
- 모각코 상세 게시글 페이지에서 사용되는 기능에 대한 API를 작성하고 연동합니다.
- react-query를 사용하면 서버 상태를 마치 전역 상태처럼 어떤 컴포넌트에서든 자유롭게 불러올 수 있는데, 이 경우 서버 상태에 대하여 부모-자식 컴포넌트 간 props 전달이 굳이 필요할지, 필요하다면 그 중 어떤 값을 전달해야 할지 고민이 되었습니다.
- 각자의 컴포넌트 안에서 `useQuery`로 불러오기: 성능에 대한 걱정도 있지만 중복 코드, 컴포넌트가 커지는 문제가 있음.
- 최상위 컴포넌트에서 불러온 후 props로 내려주기: 기존 리액트식 상태 관리 문제처럼 props drilling이 발생함.

[Feat] 모각코 상세 게시글 페이지 API 연동

---

app/frontend/src/components/MogacoDetail/index.css.ts

- 참석자 목록의 길이가 부모 요소를 넘지 않는 경우 스크롤바를 보이지 않도록 변경했습니다.

[Fix] 참석자 목록 overflow 값을 scroll에서 auto로 변경

---

app/backend/docker-compose.yml

- 백엔드 서버에 prisma 마이그레이션 정보 볼륨 마운트 되게 수정

[Fix] docker compose 스크립트 수정

---

app/backend/.gitignore
app/backend/Dockerfile
app/backend/prisma/migrations/20231124100030_init/migration.sql

- DB 마이그레이션 방법 변경
1. Prisma을 이용해서 DB 마이그레이션을 했을 때 기록을 VCS에서 관리해야 함.
2. 기존 Schema에서 변경 사항만 migrate 되도록 해야 함.
- 기존에 마이그레이션 했던 정보가 날아가지 않도록 주의 해야함.
- 기존에 마이그레이션 했던 정보를 지워야 하는 경우 소통 후 제거 합시다.
@ldhbenecia

[Fix] db 마이그레이션 로직 변경

---

app/backend/src/auth/auth.repository.ts
app/backend/src/auth/auth.service.ts

- close #177 
현재 첫 로그인을 할 때 사용자의 닉네임과 프로필 사진에 대한 정보를 알기 위해 DB에 기록하는 로직으로 변경하였습니다.
하지만 사용자는 구글에서 본인의 닉네임, 프로필 사진을 변경할 수 있습니다.
그에 대해 사용자가 로그인을 했을 때 DB에 기록되어있는 닉네임, 프로필 사진 주소가 같은 지 확인 후 다르다면 업데이트를 합니다.
[백로그 스크린샷 기록](https://ttaerrim.notion.site/375b2885383d435c9612208b67b0856f?pvs=4)

[Feat] DB 사용자 정보(닉네임, 프로필 사진 주소) 최신화 구현

---

app/backend/libs/utils/swagger.ts
app/backend/src/auth/auth.controller.ts
app/backend/src/groups/dto/response-groups.dto.ts
app/backend/src/groups/groups.controller.ts
app/backend/src/member/member.controller.ts
app/backend/src/mogaco/dto/response-participants.dto.ts
app/backend/src/mogaco/mogaco.controller.ts

- close #144 
Api Test를 위해 액세스 토큰을 입력해서 로그인 상태를 만들고 해당 Api를 테스트 하도록 합니다.

[Feat] Group Swagger 문서화 작업

---

app/frontend/src/App.tsx
app/frontend/src/main.tsx
app/frontend/src/pages/MogacoDetail/DetailHeaderButtons.tsx
app/frontend/src/queries/hooks/index.ts
app/frontend/src/queries/hooks/member.ts
app/frontend/src/queries/index.ts
app/frontend/src/queries/member.ts
app/frontend/src/utils/index.ts
app/frontend/src/utils/mocking.ts

- closed #189 
- query-key-factory에서 staleTime 옵션을 지정할 수 없어 /member/me에 대한 커스텀 훅을 따로 분리하였습니다.
- React-Query의 retry 기본 값을 false로 변경했습니다. → 더 빠른 UI 반영을 위함

[Refactor] App.tsx와 main.tsx 용도 분리 및 리팩토링

---

app/frontend/package.json
app/frontend/src/constants/url.ts
app/frontend/src/services/morakAPI.ts

- Iocal 환경에서 API를 localhost:8080로 테스트하기 위한 command를 추가했습니다.
- [Vite Env Mode](https://vitejs.dev/guide/env-and-mode.html#env-variables-and-modes)를 참고했습니다.
- `--mode test` 옵션을 붙여 실행할 경우 `import.meta.env.MODE`를 통해 test라는 문자열에 접근할 수 있어 이를 사용

[Feat] local에서 API test를 위한 command 추가

---

app/backend/libs/utils/swagger.ts
app/backend/src/auth/auth.controller.ts
app/backend/src/auth/auth.repository.ts
app/backend/src/auth/auth.service.ts

- close #188 
본래 /auth/refersh 토큰 요청 상태가 바르지 않아 오류가 발생하였던 현상을 해결합니다.
/auth/refresh API 요청을 보내는 경우 해당 사용자의 상태는 refresh_token만 존재하고 access_token은 없는 경우일 수도 있으며, 
새 액세스 토큰을 발급받아야하는 상황이기에 bearer_token은 받지않고 해당 사용자의 쿠키에 있는 refresh_token을 서버에서 추출하여
Redis에 기록되어있는 값과 비교하는 검증 절차를 걸친 후 올바른 refresh_token일 경우, 새 액세스 토큰을 발급합니다.
Swagger에서 테스트를 진행하기 위해 @ApiCookieAuth()를 추가하여서 쿠키를 넣는 칸을 추가하였습니다.
[백로그 스크린샷 기록](https://ttaerrim.notion.site/auth-refresh-f4195ecdf4c54f88a8aa173d3cc097cb?pvs=4)

[Feat] /auth/refresh API 보수 및 Swagger

---

app/backend/src/mogaco/dto/response-mogaco.dto.ts
app/backend/src/mogaco/dto/response-participants.dto.ts
app/backend/src/mogaco/mogaco.repository.ts
packages/apitype/dto/response/mogaco.ts
packages/apitype/dto/response/participant.ts

- close #202 
현재 프론트엔드단에서 API를 두번 씩 호출하는 상황이 생겼습니다.
@ttaerrim 님께서 설명해주시고 API 커넥션이 여러 번 일어나는 것은 좋지 않다고 판단되어
단 한번의 API 커넥션으로 필요한 정보를 전부 전달할 수 있도록 변경하였습니다.
추가적으로 필요한 사항 있으면 언제든지 말씀해주시면 감사하겠습니다.

[Feat] 특정 모각코 조회 시 참가자 목록 반환

---

app/backend/src/mogaco/dto/response-mogaco.dto.ts
app/backend/src/mogaco/mogaco.repository.ts
packages/apitype/dto/response/mogaco.ts

모각코 정보 반환할 때 그룹명도 반환해달라는 요청에 따른 구현
x

[Feat] 모각코 정보 반환 시 그룹명 추가 반환

---

app/backend/libs/utils/swagger.ts
app/backend/src/groups/groups.controller.ts
app/backend/src/groups/groups.repository.ts
app/backend/src/groups/groups.service.ts
app/backend/src/member/member.controller.ts
app/backend/src/mogaco/dto/response-mogaco.dto.ts

- close #212 
모각코를 개설할 때 사용자는 본인이 속한 그룹을 알고 그룹을 지정해서 모각코를 개설합니다.
Swagger

[Feat, Refactor] 사용자 본인 가입 그룹 확인 API 및 Swagger 보수

---

app/backend/src/groups/groups.controller.ts
app/backend/src/groups/groups.repository.ts
app/backend/src/groups/groups.service.ts
app/backend/src/member/member.controller.ts
app/backend/src/member/member.service.ts
app/backend/src/mogaco/dto/response-mogaco.dto.ts
app/backend/src/mogaco/dto/response-participants.dto.ts
app/backend/src/mogaco/mogaco.controller.ts
app/backend/src/mogaco/mogaco.repository.ts
app/backend/src/mogaco/mogaco.service.ts
packages/apitype/dto/request/api.ts
packages/apitype/dto/response/mogaco.ts
packages/apitype/dto/response/participant.ts

- close #222 
- close #223 
/member/me에 대한 오류를 다시 한번 수정합니다.
id값이나 사용하지 않는 데이터 반환을 최소화합니다.
[스크린샷 기록](https://ttaerrim.notion.site/3e8d03ddf9114910bbceb1f34707ce0b?pvs=4)
- id, socialType 같은 값을 제외했습니다.
- 조회 시 그룹 아이디, 참석자 정보에서는 소셜타입, 생성일에 대한 데이터를 제외하고 보냅니다.
- 해당 API는 헤더에 bearer_token으로 액세스 토큰을 넣어 함께 전달합니다.
- 추가적으로 서버에서 요청하는 사용자의 브라우저에서 쿠키를 추출하여서 정보를 반환합니다.
- 고로 클라이언트에서는 bearer_token만 넣어서 전달하고 쿠키가 잘 심어져있다면 정상적으로 동작하는 것으로 기대됩니다.

[Refactor/Fix] 불필요한 데이터 반환 제외 및 /member/me API 수정

---

app/frontend/src/components/Header/index.css.ts
app/frontend/src/components/Layout/index.tsx
app/frontend/src/components/Modal/InputModal.tsx
app/frontend/src/components/Modal/ModalContainer.tsx
app/frontend/src/components/Modal/index.css.ts
app/frontend/src/components/Modal/index.tsx
app/frontend/src/components/Sidebar/index.css.ts
app/frontend/src/components/index.ts
app/frontend/src/hooks/index.ts
app/frontend/src/hooks/useModal.ts
app/frontend/src/stores/index.ts
app/frontend/src/stores/modal.ts

- closed #211
- 모달을 공통으로 사용하기 위한 portal과 hook을 만들었습니다.
- header와 sidebar의 z-index를 조절하였습니다. (header가 999로 설정되어 있었는데 불필요하게 값이 크다고 생각했어요.)
- createPortal을 사용했습니다. `id=root`인 div의 외부에서 모달을 사용합니다. <sup>[[1]](#ref1)</sup>
- `<dialog>` 내에서 `method=dialog`인 form 안에서 버튼을 사용할 경우, ref를 사용하지 않고 모달을 닫을 수 있어 모달 내부 코드를 수정했습니다.
- modal의 열림 상태, 보여 줄 modal을 관리할 atom을 만들었습니다.
- 모달을 사용할 때는 useModal을 사용합니다.
```typescript
const { openModal } = useModal();
const onClickModal = () => {
openModal(
<InputModal onClickConfirm={() => console.log('hi')} description="hi" />,
);
};
```
https://github.com/boostcampwm2023/web17_morak/assets/43867711/7b24a08e-8beb-4e14-93d4-c8852975880b
<a id='ref1'>createPortal</a>

[Feat] 공통 모달 구현

---

app/frontend/src/components/MogacoItem/index.tsx

- 변경된 스키마에 맞게 모각코 아이템에서 인원 수 표시를 제거하였습니다.

[Fix] 모각코 아이템에서 인원 표시 제거

---

app/frontend/src/mocks/mogaco.ts
app/frontend/src/pages/Calendar/CalendarView.tsx
app/frontend/src/pages/Calendar/useMogacoQuery.ts
app/frontend/src/queries/mogaco.ts
app/frontend/src/services/mogaco.ts

- 캘린더 페이지에서 월별 모각코 기록을 가져와 달력 화면에 보여 줍니다.
- useQuery를 사용해 가져온 데이터를 select 옵션을 사용하여 필터링된 data 값을 리턴할 수 있습니다.
- API 작업 중인 상태이고, mocking으로 작업했습니다.
https://github.com/boostcampwm2023/web17_morak/assets/43867711/3341313f-b62e-40b8-8262-89721a30eb5e

[Feat] Calendar API 연결

---

app/frontend/src/pages/MogacoDetail/DetailHeaderButtons.tsx
app/frontend/src/pages/MogacoDetail/useDeleteModal.tsx

- window.alert로 임시 구현되어 있던 부분 모달로 교체
- useDeleteModal 커스텀 훅 만들어 사용
https://github.com/boostcampwm2023/web17_morak/assets/43867711/02b1ead5-8502-4be6-bc92-86ea6d1c545f

[Modify] 글 삭제 버튼 클릭 시 모달 연결

---

app/frontend/src/pages/MogacoPost/Controller/PostGroupId.tsx
app/frontend/src/pages/MogacoPost/Controller/group.css.ts
app/frontend/src/pages/MogacoPost/index.tsx
app/frontend/src/queries/group.ts
app/frontend/src/queries/index.ts
app/frontend/src/services/group.ts
app/frontend/src/services/index.ts

- 글 작성 시 유저가 가입된 그룹만 선택할 수 있도록 select box로 선택할 수 있게 합니다.
- select box는 디폴트로 그룹의 첫 번째 아이템이 선택된 것처럼 보이나, select를 직접 열어 옵션을 변경하지 않으면 rhf에는 반영되지 않는 이슈가 있어 setValue 메소드로 groups을 받아왔을 때 groupId에 명시적으로 첫 번째로 가지고 있는 그룹의 아이디를 지정해 주었습니다.
- 추가 필요 작업

[Modify] 글 작성 시 가입된 그룹 선택

---

app/backend/src/mogaco/dto/response-mogaco.dto.ts
app/backend/src/mogaco/mogaco.controller.ts
app/backend/src/mogaco/mogaco.repository.ts
app/backend/src/mogaco/mogaco.service.ts
packages/apitype/dto/response/mogaco.ts

- close #234 
기간 별로 게시글을 조회합니다.
'2023-11', '2023-11-23' 둘 다 인식하도록 동작합니다.
다만 월은 무조건 두 자릿수로 '2023-04' 이런 식으로 작성이 되어야 합니다.
엔드포인트를 통일하기 위해 컨트롤러단에서 두 기능을 분기하였습니다.
NestJS의 라우팅 시스템으로 인해 상당한 양의 고통을 받았습니다.
[NestJS 라우팅으로 인한 오류 정리](https://velog.io/@ldhbenecia/NestJS-Validation-failed-%EB%9D%BC%EC%9A%B0%ED%8C%85-%EC%8B%9C%EC%8A%A4%ED%85%9C%EC%9C%BC%EB%A1%9C-%EC%9D%B8%ED%95%9C-%EC%98%A4%EB%A5%98)
x

[Feat] 모각코 기간 별 조회 기능

---

app/frontend/src/components/Map/index.tsx

- 모각코 데이터의 좌표값이 없는 경우 마커를 찍는 과정에서 지도가 정상적으로 렌더링되지 않습니다.
- 좌표값이 있을 때만 마커를 찍도록 수정하였습니다.
- #238 에서 언급된 `Property 'coord' does not exist on type 'ResponseMogacoDto'.` 에러와는 상관 없습니다.

[Fix] 모각코 데이터의 좌표값이 없는 경우 처리

---

app/backend/src/groups/groups.controller.ts
app/backend/src/groups/groups.repository.ts
app/backend/src/mogaco/mogaco.controller.ts
app/backend/src/mogaco/mogaco.repository.ts

- close #247 
groups API 코드에서 async 메소드로 잡혀있는데 그 안에는 then으로 받더라
시간 제한 둘 때 이상-이하보다는 이상-미만이 더 안전하다고 생각
getAllMogaco(): mogaco 없으면 404 응답하던데 응답 형식은 array더라, 이 경우 404가 조금 애매함. API endpoint가 없어서인지 결과가 없어서인지 애매.
⇒ 결과 데이터 0개는 null이 아님. 공집합.
⇒ 한 개가 아닌 n개의 데이터를 내려주는 경우 공집합도 데이터가 존재하는 걸로 침
Prisma에서 Date 관련 구문 gte(이상), lte(이하), gt(초과), lt(미만)으로 되어있으나 현재
```typescript
// 231129 ldhbenecia | 사용자가 날짜만 입력한 경우 (e.g., '2023-11')
if (date.length === 7) {
startDate = new Date(`${date}-01T00:00:00.000Z`);
endDate = new Date(`${date}-31T23:59:59.999Z`);
} else {
// 231129 ldhbenecia | 사용자가 날짜와 일자를 입력한 경우 (e.g., '2023-11-25')
startDate = new Date(`${date}T00:00:00.000Z`);
endDate = new Date(`${date}T23:59:59.999Z`);
```
여기서 이상, 미만으로 바꾸라는 피드백을 받아서 본래 gte, lt로 이상, 미만으로 받았으나 이상, 이하로 해결함
gte, lte 사용
> 기능 작업에 대한 …

[Refactor] 멘토링 피드백 반영

---

app/frontend/src/components/Button/index.tsx
app/frontend/src/components/Input/index.tsx
app/frontend/src/components/Modal/MapModal.css.ts
app/frontend/src/components/Modal/MapModal.tsx
app/frontend/src/constants/env.ts
app/frontend/src/constants/index.ts
app/frontend/src/pages/MogacoPost/Controller/PostAddress.tsx
app/frontend/src/pages/MogacoPost/index.tsx
app/frontend/src/queries/index.ts
app/frontend/src/queries/tmap.ts
app/frontend/src/services/index.ts
app/frontend/src/services/tmap.ts
app/frontend/src/types/index.ts
app/frontend/src/types/tmap.ts

- #261 
- 장소 검색 시 API 불러오고 그를 사용해 장소 입력하는 부분 1차 구현
- 주소 입력창 클릭 시 맵 모달을 띄워 장소 검색할 수 있도록 합니다. input과 datalist 태그를 사용하여 구현하려고 했으나, 원하는 동작은 주소는 사용자가 직접 입력한 텍스트가 아닌 API 검색 결과를 통한 오직 풀 주소만 입력하게 하고 싶었기 때문에 input과 ul, li 태그를 사용하여 구현하는 방향으로 수정했습니다.
- 자세한 내용은 [노션](https://www.notion.so/ttaerrim/be56a4fcbd3f4fe9a6f29525b492ab0c?p=1645d224b33d4f968ee81dca843bd8ae&pm=s)에 작성 중
- 컴포넌트가 점점 길어지고 있는데, 컴포넌트 분리는 기능 구현 완료 후 작업할 예정입니다.
https://github.com/boostcampwm2023/web17_morak/assets/43867711/05577c97-154f-42bf-978d-6ff14f3f7d90

[Feat] 폼 작성 시 장소 API를 통해 입력 

---

app/frontend/src/components/Map/Marker.tsx
app/frontend/src/components/Map/index.tsx
app/frontend/src/components/Modal/MapModal/index.tsx
app/frontend/src/components/Modal/MapModal/useMap.ts
app/frontend/src/queries/tmap.ts
app/frontend/src/services/tmap.ts
app/frontend/src/types/global.d.ts
app/frontend/src/types/tmap.ts

- #261 
- 사용자가 직접 지도를 클릭해 위치를 선택하는 기능 구현
- 좌표를 주소로 변환해 주는 TMap API(reverseGeocoding) 사용
- Marker 컴포넌트를 new Tmapv2.marker 메소드의 parameter와 동일하게 사용할 수 있도록 latitude/longitude → position으로 변경했습니다. @LEEJW1953 
- 지도 클릭 시 마커를 띄우며 고민했던 사항은 [노션](https://www.notion.so/ttaerrim/TMAP-API-1645d224b33d4f968ee81dca843bd8ae?pvs=4#b13220ed7188418ba00b3f88c8eade26)에 정리해 두었으니 참고바랍니다. (마커 여러 개 찍히는 문제, 장소/지도 클릭 시 생기는 마커 문제, 좌표가 변경될 때마다 장소 렌더링 관련 문제)
https://github.com/boostcampwm2023/web17_morak/assets/43867711/936396d7-1504-43f8-a17f-ab26fac3f6f5

[Modify] 장소 선택 시 지도에서 장소를 직접 선택할 수 있는 기능 추가

---

app/frontend/src/components/Modal/MapModal/index.tsx

- #297 
- dialog 내 `<form method='dialog'>`를 사용하면 엔터 키를 눌렀을 때 cancleEvent가 동작하면서 모달이 닫히는 현상이 발생합니다. 현재 모달의 백그라운드를 ::backdrop 속성이 아닌 div를 사용하고 있어 modalOpenedAtom의 상태에 의해 백그라운드가 표시되는데, 엔터를 눌렀을 경우는 modalOpenedAtom 상태를 조정하는 것이 아닌 단순 modal의 open 상태만 변경되어 발생하는 버그입니다. 임시로 form 태그를 div 태그로 변경하여 엔터 키를 눌렀을 때도 모달이 닫히지 않도록 처리했습니다.

[Bug] 맵 모달에서 엔터 누르면 모달만 닫히는 버그 픽스

---

app/frontend/src/components/Auth/index.tsx
app/frontend/src/components/Header/index.css.ts
app/frontend/src/components/Header/index.tsx
app/frontend/src/components/Header/useClickMenu.ts
app/frontend/src/components/Header/useLoginRequireModal.tsx
app/frontend/src/components/Header/useMenu.tsx
app/frontend/src/components/Modal/index.tsx
app/frontend/src/components/index.ts
app/frontend/src/constants/Header.ts
app/frontend/src/constants/index.ts
app/frontend/src/hooks/useRouter.tsx

- closed #317 
- 비로그인 시 다른 라우터에 접근하는 것을 막음
- AuthRequired 컴포넌트를 추가하여 사용했습니다. 
- 헤더 변경 사항 @LEEJW1953 
- NavLink 대신 onClick 핸들러를 사용해야 하여, ul 태그로 변경했습니다.
- 헤더 스타일 파일을 리팩토링했습니다. 
- sideMenuButton active를 selector를 사용하도록 변경
- vars.color 구조 분해 할당으로 사용
- 헤더의 constants를 useMenu 훅으로 사용하도록 변경 (프로필까지 map 고차 함수 사용을 위함)
로그인 시 
https://github.com/boostcampwm2023/web17_morak/assets/43867711/466d7888-b76d-403c-a902-9a9a37a725e3
비로그인 시 
https://github.com/boostcampwm2023/web17_morak/assets/43867711/21d9b1b0-3b1d-4cfc-98da-79eb6363b25b

[Feat] 비로그인 시 메인 외 다른 라우터에 접근 방지

---

app/frontend/src/pages/Mogaco/MogacoList.tsx
app/frontend/src/queries/mogaco.ts
app/frontend/src/services/mogaco.ts

- close #345 
- 모각코 페이지 요청 시 page 인자를 '1'로 전달하도록 수정합니다.
- 아직 페이지네이션은 구현되지 않은 상태입니다.

[Fix] 모각코 페이지 요청 시 기본 page를 '1'로 설정

---

app/backend/src/mogaco-boards/mogaco-boards.controller.ts
app/backend/src/mogaco-boards/mogaco-boards.repository.ts
app/backend/src/mogaco-boards/mogaco-boards.service.ts

- close #348 
페이지네이션이 미적용된 기본
`http://localhost:8080/posts`의 Get 요청 코드도 추가합니다.
해당 기능은 지도에서 쓰입니다.
이로써 모각코 조회 부분은 
기본 조회
페이지네이션 조회
기간별 조회
세 기능을 가집니다.
게시글을 생성할 때 그룹이 가입되어있지않은 경우에 대해 클라이언트에서 처리를 해주고 있으나 이중으로 추가합니다.
@LEEJW1953 @js43o @ttaerrim 
클라이언트분들 확인 부탁드립니다.
페이지네이션 시 기본 페이지를 1로 설정하였으나 제외하였습니다.
클라이언트에서 처리해주시기 바랍니다.

[Feat] 페이지네이션 미적용 및 오류 예외처리 추가

---

app/frontend/src/components/Input/Textarea.css.ts
app/frontend/src/components/Label/index.tsx
app/frontend/src/components/Sidebar/Contents/Chatting/index.css.ts
app/frontend/src/components/Sidebar/Contents/Mogaco/GroupWrapper.tsx
app/frontend/src/components/Sidebar/Contents/Mogaco/MogacoInfo.tsx
app/frontend/src/components/Sidebar/Contents/Mogaco/index.css.ts
app/frontend/src/components/Sidebar/index.css.ts

close #330
- 사이드바 컴포넌트의 반응형 UI를 개선합니다.
- **Textarea, Label 컴포넌트에 약간의 변경사항이 추가되었습니다.** (자세한 것은 파일 변경사항을 확인해 주세요)
- 모각코 정보 사이드바에서 실제 모각코 그룹명을 사용하도록 변경했습니다. (반응형 작업은 아니어서 말씀드립니다)
- 채팅 UI
https://github.com/boostcampwm2023/web17_morak/assets/50646827/a0c57ccc-5d04-4403-8897-e0ce305313b7
- 모각코 정보
https://github.com/boostcampwm2023/web17_morak/assets/50646827/f660a91c-a9af-4752-9e47-e4b6ae152069

[Refactor] 사이드바 컴포넌트 반응형 UI 개선

---

app/frontend/src/pages/Profile/MyProfile/index.css.ts
app/frontend/src/pages/Profile/MyProfile/index.tsx
app/frontend/src/pages/Profile/index.css.ts
app/frontend/src/pages/Profile/index.tsx
app/frontend/src/services/auth.ts
app/frontend/src/services/index.ts

- close #319
- 현재 로그인한 사용자의 정보를 불러와서 프로필 영역에 표시합니다.
- services/auth.ts 및 logout 코드를 추가하였습니다.
- https://github.com/boostcampwm2023/web17_morak/pull/316 해당 PR 먼저 머지 후 PR 오픈하겠습니다. (종속됨)
https://github.com/boostcampwm2023/web17_morak/assets/50646827/cc54e7c8-5783-4102-949a-59844d845304
- 응답 데이터가 없는 단순 로그아웃 요청에 쿼리 커스텀 훅을 추가하는 것이 좋을지 고민하다가 일단은 쿼리 키까지만 추가하여 사용하고 있습니다. 더 좋은 의견이 있다면 말씀 부탁드립니다.

[Feat] 현재 로그인한 사용자 정보를 프로필에 표시, 로그아웃 버튼 구현

---

app/frontend/src/components/Group/GroupButton.tsx
app/frontend/src/components/Group/index.css.ts
app/frontend/src/components/Group/index.tsx
app/frontend/src/styles/font.css.ts

- close #331 
- 그룹 아이템 컴포넌트의 반응형 UI를 개선합니다.
- 현재 뷰포트 너비에 따라 그룹 버튼의 위치가 위/아래로 달라지게 했습니다. (`desktop`, `mobile` 스타일 객체 선언)
- **참여한 그룹의 이름은 중요한 정보라고 생각해서 줄임 효과(ellipsis)를 넣지 않고 모두 표시되도록 하였습니다.** 처음 그룹을 생성할 때 적절히 글자 수 제한을 두는 쪽으로 가는 것이 좋을 것 같습니다.
- 줄임표를 넣어서 한 줄만 표시한다면? => `부스트캠프 웹·모바일 8기`와 `부스트캠프 웹·모바일 9기`가 모두 `부스트캠프 웹...`과 같이 표시되어 구분할 수 없는 경우가 생길 수 있음
- 인원 수 표시를 제목과 같은 줄에서 제목 밑 2번째 줄로 내렸습니다.
- 정확한 그룹 코드는 복사 버튼이 있으므로 생략해도 괜찮다고 판단하여 모바일에서 표시를 생략했습니다.
https://github.com/boostcampwm2023/web17_morak/assets/50646827/777811e5-3398-49be-8474-6917fecfa818
- 디자인에 관해 다른 의견 있으시다면 말씀 부탁드립니다!

[Refactor] 그룹 아이템 컴포넌트 반응형 UI 개선

---

app/frontend/src/components/Input/index.tsx

…하도록 리팩토링
- #361 
- Input 컴포넌트 사용 시, Input 컴포넌트의 타입으로 명시하지 않은 타입을 추가하여 사용하고 싶다면 일일이 Input 컴포넌트에 추가해야 하는 번거로움이 발생. 이를 InputHTMLAttributes 타입과 ...rest props를 사용하여 해결.

[Refactor] Input 컴포넌트 리팩토링

---

app/frontend/src/pages/Mogaco/ErrorPage.css.ts
app/frontend/src/pages/Mogaco/ErrorPage.tsx
app/frontend/src/pages/Mogaco/MogacoList.tsx
app/frontend/src/pages/Mogaco/NoContents.css.ts
app/frontend/src/pages/Mogaco/NoContents.tsx

- close #332 
- 모각코 데이터를 불러오는 데 실패하거나 현재 속한 그룹에 등록된 모각코 게시글이 0개인 경우 적절한 UI를 표시합니다.
- 페칭 실패
- 게시글 0개

[Refactor] 모각코 게시글 데이터 페칭 에러 및 등록된 게시글이 0개일 때 UI 표시

---

app/frontend/src/pages/MogacoPost/Controller/PostDate.tsx
app/frontend/src/pages/MogacoPost/index.tsx

- #369 
- 글 작성 시 시간 초과할 경우 글 작성 버튼 활성화되지 않는 문제(이슈 참고)를 해결하기 위하여 글 작성 버튼의 disabled 속성을 삭제했습니다.
- 날짜/시간 입력이 되지 않았을 경우 rhf으로만 유효성 검사를 하기 위하여 required 속성을 제거했습니다. (기존에는 form 태그의 기능이 우선 작용)

[Bug] 글 작성 시 시간 초과할 경우 글 작성 버튼 활성화되지 않음 버그 해결

---

app/backend/package.json
app/backend/src/mogaco-boards/mogaco-boards.repository.spec.ts
app/backend/src/mogaco-boards/mogaco-boards.repository.ts

- close #393 
- close #395 
현재 모각코 상태 코드의 경우 전부 모집 중으로만 처리가 되고 있습니다.
최대 인원수에 맞아지면 모집 중 -> 모집 마감
최대 인원수에서 누군가 취소를 할 경우 모집 마감 -> 모집 중으로 변경되어야합니다.
또한 모각코 시행일자 Date가 지난 경우 상태코드를 종료로 변경해야합니다.
그리고 현재 모각코 참가를 최대 인원수를 넘겨도 계속 참여할 수 있기 때문에 그에 해당하는 오류처리도 진행하였습니다.
[개발 일지 기록](https://ttaerrim.notion.site/4a5b762b87f345d598bf87115b894ce9?pvs=4)
@ttaerrim @LEEJW1953 @js43o

[Feat] 모각코 모집 중/모집 마감/종료 필터링 구현 및 최대 인원 수 초과 시 오류 처리

---

app/backend/src/groups/dto/groups.dto.ts
app/backend/src/groups/groups.controller.spec.ts
app/backend/src/groups/groups.controller.ts
app/backend/src/groups/groups.repository.spec.ts
app/backend/src/groups/groups.repository.ts
app/backend/src/groups/groups.service.spec.ts
app/backend/src/groups/groups.service.ts
packages/apitype/dto/response/groups.ts

- close #394 
전체 그룹 조회 시 그룹 인원이 몇 명인지도 조회합니다.
@ttaerrim @LEEJW1953 @js43o

[Feat] 그룹 조회 시 해당 그룹 인원 추가 반환

---

app/frontend/src/pages/Main/index.css.ts
app/frontend/src/pages/Main/index.tsx

- close #334 
- 메인페이지 반응형 UI 개선
https://github.com/boostcampwm2023/web17_morak/assets/110762136/649331f5-98e3-46bc-ad94-aa20f53bb0ed

[Feature] 메인페이지 반응형 UI 개선

---

app/backend/src/mogaco-boards/mogaco-boards.controller.ts
app/backend/src/mogaco-boards/mogaco-boards.repository.ts
app/backend/src/mogaco-boards/mogaco-boards.service.ts

- close #396 
프로필 페이지에서 사용자가 현재 속한 모각코를 조회하기 위한 API를 구현합니다.

[Feat] 사용자가 참여한 모각코 조회 API 구현

---

app/backend/libs/utils/swagger.ts
app/backend/src/auth/auth.controller.ts
app/backend/src/auth/auth.module.ts
app/backend/src/auth/auth.repository.ts
app/backend/src/auth/auth.service.ts
app/backend/src/auth/guards/at.guard.ts
app/backend/src/auth/interface/payload.interface.ts
app/backend/src/groups/groups.controller.ts
app/backend/src/member/member.controller.ts
app/backend/src/mogaco-boards/mogaco-boards.controller.ts

- close #406 
[개발 일지](https://ttaerrim.notion.site/Cookie-Httponly-Secure-ea27c771aeef406aadc02709f587c99e?pvs=4)
[회의 기록](https://ttaerrim.notion.site/930d97a2db1743d7bd61117fc9f23716?pvs=4)
프론트엔드는 API 요청을 할 때 헤더에 bearer token을 심어서 보낼 필요가 없습니다.
서버단에서 해당 요청한 사용자의 쿠키에서 액세스 토큰을 추출해내어 인가를 처리합니다.
이를 통해 클라이언트에서는 쿠키에 직접 접근할 필요가 없어지며, httponly를 걸어서 보안적으로도 이점을 취할 수 있습니다.
- 위의 개발일지, 회의 확인
@ttaerrim @js43o @LEEJW1953 
위의 개발일지를 자세히 봐주시기 바랍니다.

[Feat] 로그인 인가 처리 방식 변경 (bearer token 사용 x)

---

app/backend/src/mogaco-boards/mogaco-boards.repository.ts

본인이 속한 모각코 조회가 본인이 속한 그룹의 모각코를 불러오는 것으로 잘못되어 수정합니다.
- 현재 이 계정은 14번 하나만 참여함
@js43o

[Refactor] 본인이 참여한 모각코 조회 API 수정

---

app/frontend/src/pages/Profile/index.css.ts

그룹이 없을 경우 발생하는 스크롤 바 제거
- 내가 속한 그룹이 없을 경우 스크롤 바 발생
- 최소 높이를 지정하여 스크롤 바를 없앴습니다.
- 전
- 후

[Design] 프로필 페이지 내가 속한 그룹 스타일 수정

---

app/frontend/src/components/MogacoItem/index.tsx
app/frontend/src/pages/Profile/MyGroup/index.css.ts
app/frontend/src/pages/Profile/MyGroup/index.tsx
app/frontend/src/pages/Profile/MyMogaco/index.css.ts
app/frontend/src/pages/Profile/MyMogaco/index.tsx
app/frontend/src/pages/Profile/index.css.ts
app/frontend/src/pages/Profile/index.tsx
app/frontend/src/queries/mogaco.ts
app/frontend/src/services/mogaco.ts

- close #328 
- 현재 로그인한 사용자가 참여한 모각코 목록을 마이페이지에서 불러와 표시합니다.
- `<MyGroup>` 컴포넌트와 사용하는 스타일이 많이 겹쳐서 공통 스타일을 `index.css.ts`로 이동하였습니다.
- 참여한 모각코 있음 (3개 이상부터 스크롤 처리)
- 참여한 모각코 없음
- 데이터 페칭 에러

[Feat] 마이페이지 - 내가 참가한 모각코 추가

---

app/frontend/src/components/Sidebar/Contents/Chatting/ChatList.tsx
app/frontend/src/components/Sidebar/Contents/Chatting/TalkItem.tsx
app/frontend/src/components/Sidebar/Contents/Chatting/index.tsx
app/frontend/src/components/UserChip/index.css.ts
app/frontend/src/components/UserChip/index.tsx
app/frontend/src/hooks/useChatting.ts

- close #383 
- 채팅 도중 새로운 사용자가 입장/퇴장할 때마다 모각코 정보를 동적으로 페칭하여 참여자 정보를 불러옵니다. (닉네임 및 프로필 사진이 정상적으로 표시되지 않던 버그 수정)
- useChatting 훅에서 현재 사용자 ID를 기억하기 위한 `userIdRef` 변수를 선언했고, `joinRoom()` 및 `leaveRoom()`이 `userIdRef`를 조건으로 동작하도록 변경하였습니다.
- 기존 모각코 참여자가 참석 취소를 하여 퇴장한 경우 '알 수 없음'으로 표시하도록 하였습니다. (다시 참석하면 기존 '알 수 없음' 정보가 다시 제대로 표시됩니다)
https://github.com/boostcampwm2023/web17_morak/assets/50646827/cdeb6e88-b3ba-4604-823c-e596a1567909

[Fix] 새로운 채팅 참여자에 대한 정보를 동적으로 리페칭하도록 변경

---

app/frontend/src/components/Sidebar/Contents/Chatting/ChattingFooter.tsx

- close #381 
- 맥 환경에서 전송한 한글 채팅 메시지의 마지막 글자가 중복으로 한 번 더 전송되는 현상을 막기 위해 `e.nativeEvent.isComposing` 속성을 전송 핸들러의 조건문에 추가하였습니다.
- 맥 OS를 사용하시는 분들께 테스트를 부탁드립니다🥹
```
git fetch upstream refs/pull/426/head:test
git switch test
```

[Fix] 맥 환경에서 채팅 마지막 글자가 중복 전송되는 현상 수정

---

app/frontend/src/components/Sidebar/Contents/Mogaco/MogacoInfo.tsx
app/frontend/src/components/Sidebar/Contents/Mogaco/index.css.ts

- close #425
- 사이드바의 contents 영역의 글자가 줄바꿈되지 않아 넘치는 현상을 수정합니다.

[Fix] 사이드바 내용 overflow 수정

---

app/backend/Dockerfile
app/backend/wait-for-it.sh

- 현재 구조는 DB host의 주소가 DB로만 이루어져 있을 때 동작하였지만, 환경 변수에 따라 유동적으로 처리 되게 변경

[fix] backend Dockerfile DB ip 유동성 추가

---

app/frontend/src/components/Button/moreButton.css.ts
app/frontend/src/pages/MogacoDetail/index.css.ts
app/frontend/src/pages/MogacoDetail/index.tsx

- close #432 
- 모각코 상세 게시글 페이지에서 contents 영역의 줄바꿈이 제대로 되지 않아 텍스트가 넘치는 현상을 수정합니다.

[Fix] 모각코 상세 게시글 페이지 contents 줄바꿈 개선

---

app/frontend/src/components/Header/index.tsx
app/frontend/src/components/Pagination/index.tsx
app/frontend/src/pages/Mogaco/MogacoList.tsx

- close #444 
- 모각코 리스트 페이지(/mogaco)의 접근성을 개선합니다. (lighthouse 기준 62점 → 95점)
- [노션 개발 일지](https://www.notion.so/ttaerrim/be56a4fcbd3f4fe9a6f29525b492ab0c?p=5e26158dc5254aba9b6bff2d706be07d&pm=s)에 작업 과정을 기록하고 있습니다.

[Refactor] 헤더 및 모각코 리스트 페이지 접근성 개선

---

app/frontend/src/pages/MogacoDetail/DetailInfo.tsx
app/frontend/src/types/tmap.ts

- close #387
- 모각코 상세 글 지도 static map으로 변경
- 상세 페이지에서 움직일 수 있는 지도를 사용하는 것은 지도 api를 통한 네트워크 요청 면에서 오버스펙이라고 생각하여 static map으로 변경하였습니다.

[Feature] 모각코 상세 글 지도 static map으로 변경

---

app/frontend/src/components/FieldLabel/index.css.ts
app/frontend/src/components/Input/Textarea.tsx
app/frontend/src/components/Input/index.css.ts

- https://github.com/boostcampwm2023/web17_morak/issues/361
- Textarea 컴포넌트의 props를 Input과 동일한 형태로 맞추었습니다.
- 가독성을 위해 Input, Textarea 폰트 크기를 1.4rem으로 늘렸습니다.

[Refactor] Input, Textarea 컴포넌트 리팩토링

---

app/frontend/cypress.config.ts
app/frontend/cypress/e2e/login.cy.ts
app/frontend/cypress/e2e/spec.cy.ts
app/frontend/src/components/Header/index.tsx
app/frontend/src/pages/Main/index.tsx

- #440 
- 로그인/비로그인 시 메인 페이지에서 다른 페이지에 접근하는 e2e 테스트 작성
- 로그인 시 테스트는 cypress.config.ts 파일의 `ACCESS_TOKEN`에 토큰을 직접 넣어 실행해야 함. 
- CI는 어떻게 할지 고민이네요 
```typescript
import { defineConfig } from 'cypress';
export default defineConfig({
e2e: {
baseUrl: 'http://localhost:5173',
setupNodeEvents(on, config) {
// implement node event listeners here
},
},
env: {
ACCESS_TOKEN: '', // 여기에 토큰 필요
},
});
```
- 테스트가 필요한 html tag에 `data-cy=""` 속성을 추가함. 
- 추후 빌드 시 data-cy를 뺄 수 있는 방법이 있는지 찾아보면 좋을 듯.

[Test] Main 페이지 로그인/비로그인 테스트 코드 작성

---

app/frontend/src/components/Header/index.tsx
app/frontend/src/components/Header/useClickMenu.ts
app/frontend/src/components/Header/useMenu.tsx

- #460
- 스크린 리더와 키보드를 통해 헤더의 각 메뉴에 접근할 수 있도록 합니다.
https://github.com/boostcampwm2023/web17_morak/assets/50646827/3e96ffd9-cf7f-498b-874f-53a53df6facf

[Refactor] 헤더 컴포넌트 스크린 리더 & 키보드 접근성 개선

---

app/frontend/src/components/Sidebar/Contents/Chatting/ChatList.tsx
app/frontend/src/components/Sidebar/Contents/Chatting/ChattingFooter.tsx
app/frontend/src/components/Sidebar/Contents/Chatting/NotificationItem.tsx
app/frontend/src/components/Sidebar/Contents/Chatting/TalkItem.tsx
app/frontend/src/components/Sidebar/index.css.ts
app/frontend/src/components/Sidebar/index.tsx
app/frontend/src/pages/MogacoDetail/DetailInfo.tsx
app/frontend/src/pages/MogacoDetail/index.tsx
app/frontend/src/pages/MogacoPost/Controller/PostContents.tsx

- close #447
- 모각코 상세 게시글 페이지의 접근성을 개선했습니다. (lighthouse 기준 83점 -> 96점)
- 사이드바가 닫혀있을 때 `visibility: hidden` 속성을 추가하여 포커싱되지 않게 만들었습니다.

[Refactor] 모각코 상세 게시글 페이지 접근성 개선

---

app/frontend/src/components/MogacoItem/index.tsx
app/frontend/src/pages/Mogaco/MogacoList.tsx
app/frontend/src/pages/Mogaco/index.tsx
app/frontend/src/pages/MogacoDetail/DetailInfo.tsx
packages/morak-ui/src/components/Pagination/index.tsx

- close #461 
- 모각코 리스트 페이지의 스크린 리더 및 키보드 접근성을 개선합니다.
https://github.com/boostcampwm2023/web17_morak/assets/50646827/92da6c86-9f16-4f3b-85f1-961c515843b2

[Refactor] 모각코 리스트 페이지 스크린 리더 & 키보드 접근성 개선

---

app/frontend/src/components/Sidebar/index.css.ts
app/frontend/src/components/Sidebar/index.tsx

- close #483
- 사이드바가 닫혀있을 때 채팅 컴포넌트가 마운트되지 않아 실시간 정보 갱신이 안 되는 현상을 수정합니다.

[Fix] 채팅 UI가 닫혀있을 때 동적 데이터 페칭 버그 수정

---

app/backend/src/groups/groups.repository.spec.ts
app/backend/src/mogaco-boards/mogaco-boards.repository.spec.ts

[Test] 모각코, 그룹 모집 필터링, 오류 처리 테스트

---

app/backend/src/mogaco-boards/mogaco-boards.repository.ts

- close #497 
현재 프로필에서 내가 참여한 모각코 조회시 이미 제거된 모각코임에도 리스트에 표시 됨
이 현상을 제거하기 위해 삭제된 모각코는 반환 안함

[Feat] 내가 참여한 모각코 조회 시 삭제된 모각코 제외 반환

---

app/frontend/src/components/MogacoItem/index.css.ts
app/frontend/src/components/MogacoItem/index.tsx
app/frontend/src/components/Sidebar/Contents/Mogaco/TitleWrapper.tsx
packages/morak-ui/src/components/Label/index.css.ts

- close #493 
- 모각코 아이템, 모각코 정보 사이드바에서 라벨 색상을 해당 모각코의 모집 상태에 따라 변경합니다.

[Refactor] 모각코 상태에 따라 라벨 색상 변경

---

app/backend/src/groups/groups.controller.ts
app/backend/src/groups/groups.repository.ts
app/backend/src/groups/groups.service.ts

- close #510 
특정 그룹 정보 반환 API 구현
- 기존의 http://localhost:8080/groups/1/groups 엔드 포인트를 http://localhost:8080/groups/1/members로 변경
@js43o 
@LEEJW1953 
@ttaerrim 
기존의 API 엔드포인트가 변경되었으니 확인 후 수정 부탁드립니다.

[Feat] 특정 그룹 정보 반환 API 구현

---

app/backend/prisma/migrations/20240129073403_commit_c91c5f7/migration.sql
app/backend/prisma/schema.prisma

- 그룹 가입 신청 및 참여 코드 스키마 DB 추가
@ldhbenecia

[Feat] 그룹 참여코드 및 가입 신청 스키마에 대한 db 추가

---

app/backend/prisma/migrations/20240129084512_commit_3de1a19/migration.sql
app/backend/prisma/schema.prisma

[Feat] DB 스키마 파일 수정

---

app/backend/src/groups/dto/create-groups.dto.ts
app/backend/src/groups/groups.controller.ts
app/backend/src/groups/groups.repository.ts
app/backend/src/groups/groups.service.ts
packages/apitype/dto/request/groups.ts
packages/apitype/dto/response/groups.ts

- close #518 
@ccxz84 
@ttaerrim 
@js43o 
@LEEJW1953 
현재 그룹 타입 아이디 값을 숫자 값으로 받는데 숫자 값별로 어떠한 경우를 처리하는지에 대한 결정이 필요합니다.

[Feat] 그룹 생성 시 그룹장, 그룹 타입 id 반환

---

app/backend/src/groups/groups.controller.ts
app/backend/src/groups/groups.repository.ts
app/backend/src/groups/groups.service.ts

- close #525 
현재 결과 멤버 카운트가 0으로 조회됨
그룹을 생성하고 그룹에 해당 방장이 insert가 되지 않는 현상으로 추정
그룹 생성하고 바로 그룹 가입 처리
@ttaerrim @js43o @LEEJW1953 프론트분들 확인 부탁드립니다.

[Feat] 그룹 생성 시 GroupAccessCode 생성 및 DB 저장
